insert into Course (c_id, title, credits, d_id) values (1, 'NBAR', 3, 11);
insert into Course (c_id, title, credits, d_id) values (2, 'HR Metrics', 3, 11);
insert into Course (c_id, title, credits, d_id) values (3, 'FDM', 3, 5);
insert into Course (c_id, title, credits, d_id) values (4, 'NFL', 3, 11);
insert into Course (c_id, title, credits, d_id) values (5, 'FBCB2', 3, 9);
insert into Course (c_id, title, credits, d_id) values (6, 'Rapid Prototyping', 3, 1);
insert into Course (c_id, title, credits, d_id) values (7, 'IP Networking', 3, 9);
insert into Course (c_id, title, credits, d_id) values (8, 'NHL', 3, 12);
insert into Course (c_id, title, credits, d_id) values (9, 'NFPA 101', 3, 10);
insert into Course (c_id, title, credits, d_id) values (10, 'SBMS', 3, 2);
insert into Course (c_id, title, credits, d_id) values (11, 'RFQ', 3, 2);
insert into Course (c_id, title, credits, d_id) values (12, 'WHIMS', 3, 5);
insert into Course (c_id, title, credits, d_id) values (13, 'MLA', 3, 11);
insert into Course (c_id, title, credits, d_id) values (14, 'Oncology', 3, 3);
insert into Course (c_id, title, credits, d_id) values (15, 'Psychological Testing', 3, 12);
insert into Course (c_id, title, credits, d_id) values (16, 'Olfaction', 3, 7);
insert into Course (c_id, title, credits, d_id) values (17, 'MD-11', 3, 6);
insert into Course (c_id, title, credits, d_id) values (18, 'Knitwear', 3, 8);
insert into Course (c_id, title, credits, d_id) values (19, 'VCAT', 3, 7);
insert into Course (c_id, title, credits, d_id) values (20, 'Zope', 3, 3);
insert into Course (c_id, title, credits, d_id) values (21, 'Oracle XE', 3, 12);
insert into Course (c_id, title, credits, d_id) values (22, 'Due Diligence', 3, 7);
insert into Course (c_id, title, credits, d_id) values (23, 'Print On Demand', 3, 3);
insert into Course (c_id, title, credits, d_id) values (24, 'Toad', 3, 10);
insert into Course (c_id, title, credits, d_id) values (25, 'DNA replication', 3, 7);
insert into Course (c_id, title, credits, d_id) values (26, 'TCAS', 3, 12);
insert into Course (c_id, title, credits, d_id) values (27, 'Team Mgmt', 3, 9);
insert into Course (c_id, title, credits, d_id) values (28, 'MVVM', 3, 10);
insert into Course (c_id, title, credits, d_id) values (29, 'Health Economics', 3, 5);
insert into Course (c_id, title, credits, d_id) values (30, 'Windows XP', 3, 10);
insert into Course (c_id, title, credits, d_id) values (31, 'WPS', 3, 4);
insert into Course (c_id, title, credits, d_id) values (32, 'Twitter Marketing', 3, 5);
insert into Course (c_id, title, credits, d_id) values (33, 'CPOE', 3, 4);
insert into Course (c_id, title, credits, d_id) values (34, 'Oracle Identity Manager', 3, 5);
insert into Course (c_id, title, credits, d_id) values (35, 'Financial Advisory', 3, 3);
insert into Course (c_id, title, credits, d_id) values (36, 'OOS', 3, 3);
insert into Course (c_id, title, credits, d_id) values (37, 'Direct Marketing', 3, 9);
insert into Course (c_id, title, credits, d_id) values (38, '21 CFR', 3, 5);
insert into Course (c_id, title, credits, d_id) values (39, 'KML', 3, 7);
insert into Course (c_id, title, credits, d_id) values (40, 'EGL', 3, 2);
insert into Course (c_id, title, credits, d_id) values (41, 'UCaaS', 3, 9);
insert into Course (c_id, title, credits, d_id) values (42, 'Slovak', 3, 12);
insert into Course (c_id, title, credits, d_id) values (43, 'VMware Fusion', 3, 10);
insert into Course (c_id, title, credits, d_id) values (44, 'Cold Calling', 3, 4);
insert into Course (c_id, title, credits, d_id) values (45, 'Errors &amp; Omissions', 3, 1);
insert into Course (c_id, title, credits, d_id) values (46, 'IBM Servers', 3, 10);
insert into Course (c_id, title, credits, d_id) values (47, 'ICD-10', 3, 5);
insert into Course (c_id, title, credits, d_id) values (48, 'CBRN', 3, 6);
insert into Course (c_id, title, credits, d_id) values (49, 'Sea Kayaking', 3, 12);
insert into Course (c_id, title, credits, d_id) values (50, 'HTML Help Workshop', 3, 3);
insert into Course (c_id, title, credits, d_id) values (51, 'Aquaculture', 3, 1);
insert into Course (c_id, title, credits, d_id) values (52, 'Graphics', 3, 10);
insert into Course (c_id, title, credits, d_id) values (53, 'MBS', 3, 5);
insert into Course (c_id, title, credits, d_id) values (54, 'Pallet Jack', 3, 8);
insert into Course (c_id, title, credits, d_id) values (55, 'Erlang', 3, 12);
insert into Course (c_id, title, credits, d_id) values (56, 'Thermal Oxidation', 3, 11);
insert into Course (c_id, title, credits, d_id) values (57, 'Affiliate Marketing', 3, 7);
insert into Course (c_id, title, credits, d_id) values (58, 'Retail Sales', 3, 6);
insert into Course (c_id, title, credits, d_id) values (59, 'DSO', 3, 10);
insert into Course (c_id, title, credits, d_id) values (60, 'Kanban', 3, 2);
insert into Course (c_id, title, credits, d_id) values (61, 'Concept HDL', 3, 5);
insert into Course (c_id, title, credits, d_id) values (62, 'Target Costing', 3, 4);
insert into Course (c_id, title, credits, d_id) values (63, 'FF&amp;E Procurement', 3, 1);
insert into Course (c_id, title, credits, d_id) values (64, 'CVE', 3, 5);
insert into Course (c_id, title, credits, d_id) values (65, 'JMP', 3, 7);
insert into Course (c_id, title, credits, d_id) values (66, 'BSSAP', 3, 3);
insert into Course (c_id, title, credits, d_id) values (67, 'QKA', 3, 12);
insert into Course (c_id, title, credits, d_id) values (68, 'AMSI', 3, 11);
insert into Course (c_id, title, credits, d_id) values (69, 'Contact Centers', 3, 11);
insert into Course (c_id, title, credits, d_id) values (70, 'Web Services', 3, 4);
insert into Course (c_id, title, credits, d_id) values (71, 'GMI', 3, 12);
insert into Course (c_id, title, credits, d_id) values (72, 'Cell', 3, 11);
insert into Course (c_id, title, credits, d_id) values (73, 'DBUnit', 3, 4);
insert into Course (c_id, title, credits, d_id) values (74, 'Juniper Technologies', 3, 8);
insert into Course (c_id, title, credits, d_id) values (75, 'Nortel DMS', 3, 1);
insert into Course (c_id, title, credits, d_id) values (76, 'DWH', 3, 4);
insert into Course (c_id, title, credits, d_id) values (77, 'SRTP', 3, 9);
insert into Course (c_id, title, credits, d_id) values (78, 'OMT', 3, 10);
insert into Course (c_id, title, credits, d_id) values (79, 'Location Intelligence', 3, 12);
insert into Course (c_id, title, credits, d_id) values (80, 'UAV', 3, 9);
insert into Course (c_id, title, credits, d_id) values (81, 'VSD', 3, 3);
insert into Course (c_id, title, credits, d_id) values (82, 'QuickBooks', 3, 11);
insert into Course (c_id, title, credits, d_id) values (83, 'LNA', 3, 7);
insert into Course (c_id, title, credits, d_id) values (84, 'Design Patterns', 3, 6);
insert into Course (c_id, title, credits, d_id) values (85, 'WCCP', 3, 10);
insert into Course (c_id, title, credits, d_id) values (86, 'Blackberry', 3, 2);
insert into Course (c_id, title, credits, d_id) values (87, 'Glass', 3, 5);
insert into Course (c_id, title, credits, d_id) values (88, 'EEO Investigations', 3, 8);
insert into Course (c_id, title, credits, d_id) values (89, 'Xara', 3, 10);
insert into Course (c_id, title, credits, d_id) values (90, 'OllyDbg', 3, 12);
insert into Course (c_id, title, credits, d_id) values (91, 'Aerial Lifts', 3, 1);
insert into Course (c_id, title, credits, d_id) values (92, 'Retail', 3, 6);
insert into Course (c_id, title, credits, d_id) values (93, 'Sniffer', 3, 12);
insert into Course (c_id, title, credits, d_id) values (94, 'HCCP', 3, 12);
insert into Course (c_id, title, credits, d_id) values (95, 'OCR', 3, 8);
insert into Course (c_id, title, credits, d_id) values (96, 'BPML', 3, 6);
insert into Course (c_id, title, credits, d_id) values (97, 'NDT', 3, 3);
insert into Course (c_id, title, credits, d_id) values (98, 'Web 2.0', 3, 12);
insert into Course (c_id, title, credits, d_id) values (99, 'IEX Total View', 3, 12);
insert into Course (c_id, title, credits, d_id) values (100, 'HCAHPS', 3, 10);
insert into Course (c_id, title, credits, d_id) values (101, 'PMO Design', 3, 9);
insert into Course (c_id, title, credits, d_id) values (102, 'Wholesale Banking', 3, 8);
insert into Course (c_id, title, credits, d_id) values (103, 'VFX Supervision', 3, 12);
insert into Course (c_id, title, credits, d_id) values (104, 'Alcoholic Beverages', 3, 4);
insert into Course (c_id, title, credits, d_id) values (105, 'RS422', 3, 11);
insert into Course (c_id, title, credits, d_id) values (106, 'Zen', 3, 11);
insert into Course (c_id, title, credits, d_id) values (107, 'Bookkeeping', 3, 11);
insert into Course (c_id, title, credits, d_id) values (108, 'Cash Handling', 3, 3);
insert into Course (c_id, title, credits, d_id) values (109, 'Interviewing Skills', 3, 10);
insert into Course (c_id, title, credits, d_id) values (110, 'Call Centers', 3, 11);
insert into Course (c_id, title, credits, d_id) values (111, 'SAP Implementation', 3, 4);
insert into Course (c_id, title, credits, d_id) values (112, 'DL1', 3, 8);
insert into Course (c_id, title, credits, d_id) values (113, 'Instructional Design', 3, 10);
insert into Course (c_id, title, credits, d_id) values (114, 'Rhinoceros', 3, 9);
insert into Course (c_id, title, credits, d_id) values (115, 'Administrative Law', 3, 2);
insert into Course (c_id, title, credits, d_id) values (116, 'Valves', 3, 1);
insert into Course (c_id, title, credits, d_id) values (117, 'Retail', 3, 5);
insert into Course (c_id, title, credits, d_id) values (118, 'RTL Coding', 3, 6);
insert into Course (c_id, title, credits, d_id) values (119, 'Thermal Oxidizers', 3, 12);
insert into Course (c_id, title, credits, d_id) values (120, 'Hazardous Materials', 3, 7);
insert into Course (c_id, title, credits, d_id) values (121, 'Strategic Sourcing', 3, 3);
insert into Course (c_id, title, credits, d_id) values (122, 'Hmong', 3, 9);
insert into Course (c_id, title, credits, d_id) values (123, 'Avid Xpress', 3, 1);
insert into Course (c_id, title, credits, d_id) values (124, 'OB/GYN', 3, 10);
insert into Course (c_id, title, credits, d_id) values (125, 'Oilfield', 3, 12);
insert into Course (c_id, title, credits, d_id) values (126, 'CATIA', 3, 1);
insert into Course (c_id, title, credits, d_id) values (127, 'VNC', 3, 11);
insert into Course (c_id, title, credits, d_id) values (128, 'Guest Recovery', 3, 9);
insert into Course (c_id, title, credits, d_id) values (129, 'Board of Directors', 3, 8);
insert into Course (c_id, title, credits, d_id) values (130, 'MMS', 3, 12);
insert into Course (c_id, title, credits, d_id) values (131, 'DJ', 3, 7);
insert into Course (c_id, title, credits, d_id) values (132, 'Cycle Counting', 3, 6);
insert into Course (c_id, title, credits, d_id) values (133, 'HNW', 3, 9);
insert into Course (c_id, title, credits, d_id) values (134, 'GT Strudl', 3, 11);
insert into Course (c_id, title, credits, d_id) values (135, 'RMI', 3, 12);
insert into Course (c_id, title, credits, d_id) values (136, 'Hydrogeology', 3, 4);
insert into Course (c_id, title, credits, d_id) values (137, 'Horticulture', 3, 6);
insert into Course (c_id, title, credits, d_id) values (138, 'Human Anatomy', 3, 11);
insert into Course (c_id, title, credits, d_id) values (139, 'Yard Management', 3, 6);
insert into Course (c_id, title, credits, d_id) values (140, 'Jury Trials', 3, 10);
insert into Course (c_id, title, credits, d_id) values (141, 'GSS', 3, 8);
insert into Course (c_id, title, credits, d_id) values (142, 'PXE', 3, 6);
insert into Course (c_id, title, credits, d_id) values (143, 'PDM Works', 3, 12);
insert into Course (c_id, title, credits, d_id) values (144, 'Psychiatry', 3, 6);
insert into Course (c_id, title, credits, d_id) values (145, 'Vectorworks', 3, 1);
insert into Course (c_id, title, credits, d_id) values (146, 'SBRT', 3, 8);
insert into Course (c_id, title, credits, d_id) values (147, 'RMX', 3, 6);
insert into Course (c_id, title, credits, d_id) values (148, 'Loans', 3, 12);
insert into Course (c_id, title, credits, d_id) values (149, 'Operational Risk', 3, 3);
insert into Course (c_id, title, credits, d_id) values (150, 'SV', 3, 4);
insert into Course (c_id, title, credits, d_id) values (151, 'Online Journalism', 3, 5);
insert into Course (c_id, title, credits, d_id) values (152, 'OAM', 3, 9);
insert into Course (c_id, title, credits, d_id) values (153, 'Sheet Metal', 3, 6);
insert into Course (c_id, title, credits, d_id) values (154, 'Jewish Studies', 3, 5);
insert into Course (c_id, title, credits, d_id) values (155, 'EEO Reporting', 3, 8);
insert into Course (c_id, title, credits, d_id) values (156, 'CDISC', 3, 3);
insert into Course (c_id, title, credits, d_id) values (157, 'QR', 3, 2);
insert into Course (c_id, title, credits, d_id) values (158, 'VSOE', 3, 6);
insert into Course (c_id, title, credits, d_id) values (159, 'EBITDA Growth', 3, 11);
insert into Course (c_id, title, credits, d_id) values (160, 'HCS', 3, 8);
insert into Course (c_id, title, credits, d_id) values (161, 'Alumni Relations', 3, 9);
insert into Course (c_id, title, credits, d_id) values (162, 'FCE', 3, 10);
insert into Course (c_id, title, credits, d_id) values (163, 'uClinux', 3, 2);
insert into Course (c_id, title, credits, d_id) values (164, 'Electricity', 3, 9);
insert into Course (c_id, title, credits, d_id) values (165, 'EBSD', 3, 11);
insert into Course (c_id, title, credits, d_id) values (166, 'Agile Project Management', 3, 12);
insert into Course (c_id, title, credits, d_id) values (167, 'Legal Writing', 3, 2);
insert into Course (c_id, title, credits, d_id) values (168, 'Clinical Research', 3, 3);
insert into Course (c_id, title, credits, d_id) values (169, 'Rubber', 3, 5);
insert into Course (c_id, title, credits, d_id) values (170, 'Qbasic', 3, 7);
insert into Course (c_id, title, credits, d_id) values (171, 'Drama', 3, 6);
insert into Course (c_id, title, credits, d_id) values (172, 'Job Scheduling', 3, 7);
insert into Course (c_id, title, credits, d_id) values (173, 'Business Development', 3, 2);
insert into Course (c_id, title, credits, d_id) values (174, 'Web Design', 3, 1);
insert into Course (c_id, title, credits, d_id) values (175, 'MLP', 3, 1);
insert into Course (c_id, title, credits, d_id) values (176, 'TFF', 3, 10);
insert into Course (c_id, title, credits, d_id) values (177, 'Ventilation', 3, 8);
insert into Course (c_id, title, credits, d_id) values (178, 'OEMs', 3, 6);
insert into Course (c_id, title, credits, d_id) values (179, 'UML Tools', 3, 9);
insert into Course (c_id, title, credits, d_id) values (180, 'NFPA', 3, 4);
insert into Course (c_id, title, credits, d_id) values (181, 'Ships', 3, 6);
insert into Course (c_id, title, credits, d_id) values (182, 'TM1', 3, 9);
insert into Course (c_id, title, credits, d_id) values (183, 'JavaSE', 3, 4);
insert into Course (c_id, title, credits, d_id) values (184, 'GMRA', 3, 12);
insert into Course (c_id, title, credits, d_id) values (185, 'CTMS', 3, 9);
insert into Course (c_id, title, credits, d_id) values (186, 'NT Backup', 3, 8);
insert into Course (c_id, title, credits, d_id) values (187, 'xPON', 3, 8);
insert into Course (c_id, title, credits, d_id) values (188, 'TS2', 3, 5);
insert into Course (c_id, title, credits, d_id) values (189, 'DS3', 3, 2);
insert into Course (c_id, title, credits, d_id) values (190, 'Online Marketing', 3, 10);
insert into Course (c_id, title, credits, d_id) values (191, 'Skin Care', 3, 2);
insert into Course (c_id, title, credits, d_id) values (192, 'JBoss ESB', 3, 2);
insert into Course (c_id, title, credits, d_id) values (193, 'Avid Xpress', 3, 11);
insert into Course (c_id, title, credits, d_id) values (194, 'Development Economics', 3, 3);
insert into Course (c_id, title, credits, d_id) values (195, 'MySQLi', 3, 6);
insert into Course (c_id, title, credits, d_id) values (196, 'NPV', 3, 1);
insert into Course (c_id, title, credits, d_id) values (197, 'PKMS', 3, 3);
insert into Course (c_id, title, credits, d_id) values (198, 'FHLMC', 3, 8);
insert into Course (c_id, title, credits, d_id) values (199, 'Avaya Technologies', 3, 11);
insert into Course (c_id, title, credits, d_id) values (200, 'Xcalibur', 3, 9);
insert into Course (c_id, title, credits, d_id) values (201, 'PeopleSoft', 3, 6);
insert into Course (c_id, title, credits, d_id) values (202, 'MLRO', 3, 6);
insert into Course (c_id, title, credits, d_id) values (203, 'ADP HRB', 3, 7);
insert into Course (c_id, title, credits, d_id) values (204, 'Overhead Cranes', 3, 4);
insert into Course (c_id, title, credits, d_id) values (205, 'Intercultural Awareness', 3, 11);
insert into Course (c_id, title, credits, d_id) values (206, 'NSF', 3, 9);
insert into Course (c_id, title, credits, d_id) values (207, 'Road Safety', 3, 7);
insert into Course (c_id, title, credits, d_id) values (208, 'RDBMS', 3, 1);
insert into Course (c_id, title, credits, d_id) values (209, 'TSCA', 3, 3);
insert into Course (c_id, title, credits, d_id) values (210, 'pgAdmin', 3, 12);
insert into Course (c_id, title, credits, d_id) values (211, 'Flame AA', 3, 12);
insert into Course (c_id, title, credits, d_id) values (212, 'HGV', 3, 6);
insert into Course (c_id, title, credits, d_id) values (213, 'ATM Networks', 3, 5);
insert into Course (c_id, title, credits, d_id) values (214, 'Juniper Technologies', 3, 8);
insert into Course (c_id, title, credits, d_id) values (215, 'SQL Azure', 3, 8);
insert into Course (c_id, title, credits, d_id) values (216, 'VDI', 3, 9);
insert into Course (c_id, title, credits, d_id) values (217, 'Sleep Apnea', 3, 9);
insert into Course (c_id, title, credits, d_id) values (218, 'Cisco UCS', 3, 5);
insert into Course (c_id, title, credits, d_id) values (219, 'Private Banking', 3, 8);
insert into Course (c_id, title, credits, d_id) values (220, 'Music', 3, 12);
insert into Course (c_id, title, credits, d_id) values (221, 'TMA', 3, 3);
insert into Course (c_id, title, credits, d_id) values (222, 'HUET', 3, 3);
insert into Course (c_id, title, credits, d_id) values (223, 'HtmlUnit', 3, 6);
insert into Course (c_id, title, credits, d_id) values (224, 'Pro II', 3, 7);
insert into Course (c_id, title, credits, d_id) values (225, 'HBA', 3, 5);
insert into Course (c_id, title, credits, d_id) values (226, 'Petroleum Engineering', 3, 12);
insert into Course (c_id, title, credits, d_id) values (227, 'Luxury Travel', 3, 9);
insert into Course (c_id, title, credits, d_id) values (228, 'Safety Management Systems', 3, 1);
insert into Course (c_id, title, credits, d_id) values (229, 'WWAN', 3, 11);
insert into Course (c_id, title, credits, d_id) values (230, 'Surveying', 3, 2);
insert into Course (c_id, title, credits, d_id) values (231, 'Ffmpeg', 3, 7);
insert into Course (c_id, title, credits, d_id) values (232, 'Czech', 3, 11);
insert into Course (c_id, title, credits, d_id) values (233, 'AWS CWI', 3, 4);
insert into Course (c_id, title, credits, d_id) values (234, 'DOT Regulations', 3, 12);
insert into Course (c_id, title, credits, d_id) values (235, 'Subversion', 3, 7);
insert into Course (c_id, title, credits, d_id) values (236, 'Corporate Governance', 3, 5);
insert into Course (c_id, title, credits, d_id) values (237, 'Interest Rate Derivatives', 3, 10);
insert into Course (c_id, title, credits, d_id) values (238, 'Design for Manufacturing', 3, 3);
insert into Course (c_id, title, credits, d_id) values (239, 'Audio Editing', 3, 4);
insert into Course (c_id, title, credits, d_id) values (240, 'Global Custody', 3, 6);
insert into Course (c_id, title, credits, d_id) values (241, 'Oracle Identity Manager', 3, 2);
insert into Course (c_id, title, credits, d_id) values (242, 'Capital Markets', 3, 11);
insert into Course (c_id, title, credits, d_id) values (243, 'Investment Properties', 3, 11);
insert into Course (c_id, title, credits, d_id) values (244, 'RBAC', 3, 12);
insert into Course (c_id, title, credits, d_id) values (245, 'Object Oriented Modeling', 3, 6);
insert into Course (c_id, title, credits, d_id) values (246, 'XTRACT', 3, 7);
insert into Course (c_id, title, credits, d_id) values (247, 'Slip &amp; Fall', 3, 11);
insert into Course (c_id, title, credits, d_id) values (248, 'Erlang', 3, 8);
insert into Course (c_id, title, credits, d_id) values (249, 'Executive Administrative Assistance', 3, 9);
insert into Course (c_id, title, credits, d_id) values (250, 'Affirmative Action', 3, 1);
insert into Course (c_id, title, credits, d_id) values (251, 'SAP BI', 3, 12);
insert into Course (c_id, title, credits, d_id) values (252, 'Agency MBS', 3, 6);
insert into Course (c_id, title, credits, d_id) values (253, 'Photography', 3, 7);
insert into Course (c_id, title, credits, d_id) values (254, 'XACT', 3, 7);
insert into Course (c_id, title, credits, d_id) values (255, 'Toyota Production System', 3, 7);
insert into Course (c_id, title, credits, d_id) values (256, 'Pallet Jack', 3, 9);
insert into Course (c_id, title, credits, d_id) values (257, 'Grievances', 3, 6);
insert into Course (c_id, title, credits, d_id) values (258, 'Affirmative Action', 3, 4);
insert into Course (c_id, title, credits, d_id) values (259, 'MTT', 3, 2);
insert into Course (c_id, title, credits, d_id) values (260, 'TMW', 3, 4);
insert into Course (c_id, title, credits, d_id) values (261, 'Business Intelligence', 3, 8);
insert into Course (c_id, title, credits, d_id) values (262, 'JTAG', 3, 11);
insert into Course (c_id, title, credits, d_id) values (263, 'Yard Work', 3, 7);
insert into Course (c_id, title, credits, d_id) values (264, 'Healthcare Consulting', 3, 2);
insert into Course (c_id, title, credits, d_id) values (265, 'Bonds', 3, 4);
insert into Course (c_id, title, credits, d_id) values (266, 'Legal Documents', 3, 5);
insert into Course (c_id, title, credits, d_id) values (267, 'Electricians', 3, 6);
insert into Course (c_id, title, credits, d_id) values (268, 'TV Distribution', 3, 2);
insert into Course (c_id, title, credits, d_id) values (269, 'Wine Tasting', 3, 9);
insert into Course (c_id, title, credits, d_id) values (270, 'Military Aviation', 3, 4);
insert into Course (c_id, title, credits, d_id) values (271, 'Durable Medical Equipment', 3, 9);
insert into Course (c_id, title, credits, d_id) values (272, 'MS Excel Pivot Tables', 3, 10);
insert into Course (c_id, title, credits, d_id) values (273, 'CDS', 3, 3);
insert into Course (c_id, title, credits, d_id) values (274, 'Electrical Controls', 3, 10);
insert into Course (c_id, title, credits, d_id) values (275, 'Key Account Management', 3, 5);
insert into Course (c_id, title, credits, d_id) values (276, 'Music', 3, 8);
insert into Course (c_id, title, credits, d_id) values (277, 'Dry Eye', 3, 8);
insert into Course (c_id, title, credits, d_id) values (278, 'SQL', 3, 3);
insert into Course (c_id, title, credits, d_id) values (279, 'Hummingbird DM', 3, 11);
insert into Course (c_id, title, credits, d_id) values (280, 'uDig', 3, 2);
insert into Course (c_id, title, credits, d_id) values (281, 'Business Objects Data Integrator', 3, 3);
insert into Course (c_id, title, credits, d_id) values (282, 'Drip Irrigation', 3, 5);
insert into Course (c_id, title, credits, d_id) values (283, 'Process Piping Design', 3, 7);
insert into Course (c_id, title, credits, d_id) values (284, 'FCL', 3, 5);
insert into Course (c_id, title, credits, d_id) values (285, 'Fine Art', 3, 10);
insert into Course (c_id, title, credits, d_id) values (286, 'TM1', 3, 3);
insert into Course (c_id, title, credits, d_id) values (287, 'Fixed Income', 3, 8);
insert into Course (c_id, title, credits, d_id) values (288, 'Business Strategy', 3, 10);
insert into Course (c_id, title, credits, d_id) values (289, 'YUM', 3, 9);
insert into Course (c_id, title, credits, d_id) values (290, 'DC-10', 3, 3);
insert into Course (c_id, title, credits, d_id) values (291, 'Data Guard', 3, 1);
insert into Course (c_id, title, credits, d_id) values (292, 'Lyophilization', 3, 8);
insert into Course (c_id, title, credits, d_id) values (293, 'BMX', 3, 6);
insert into Course (c_id, title, credits, d_id) values (294, 'Start-up Environment', 3, 10);
insert into Course (c_id, title, credits, d_id) values (295, 'PPV', 3, 8);
insert into Course (c_id, title, credits, d_id) values (296, 'Kaizen Blitz', 3, 9);
insert into Course (c_id, title, credits, d_id) values (297, 'Computer Games', 3, 4);
insert into Course (c_id, title, credits, d_id) values (298, 'Scientific Writing', 3, 5);
insert into Course (c_id, title, credits, d_id) values (299, 'Microsoft Dynamics NAV', 3, 1);
insert into Course (c_id, title, credits, d_id) values (300, 'International Human Rights', 3, 8);
insert into Course (c_id, title, credits, d_id) values (301, 'Qbasic', 3, 3);
insert into Course (c_id, title, credits, d_id) values (302, 'Hydrography', 3, 5);
insert into Course (c_id, title, credits, d_id) values (303, 'XFP', 3, 8);
insert into Course (c_id, title, credits, d_id) values (304, 'Kernel Programming', 3, 2);
insert into Course (c_id, title, credits, d_id) values (305, 'Slate', 3, 1);
insert into Course (c_id, title, credits, d_id) values (306, 'GCS', 3, 8);
insert into Course (c_id, title, credits, d_id) values (307, 'VCT', 3, 6);
insert into Course (c_id, title, credits, d_id) values (308, 'Automotive Engineering', 3, 11);
insert into Course (c_id, title, credits, d_id) values (309, 'Dynamics', 3, 7);
insert into Course (c_id, title, credits, d_id) values (310, 'Turkish', 3, 10);
insert into Course (c_id, title, credits, d_id) values (311, 'Commercial Banking', 3, 6);
insert into Course (c_id, title, credits, d_id) values (312, 'PCIe', 3, 5);
insert into Course (c_id, title, credits, d_id) values (313, 'SGML', 3, 2);
insert into Course (c_id, title, credits, d_id) values (314, 'Warehousing', 3, 2);
insert into Course (c_id, title, credits, d_id) values (315, 'Geometric Dimensioning &amp; Tolerancing', 3, 3);
insert into Course (c_id, title, credits, d_id) values (316, 'Inspection', 3, 10);
insert into Course (c_id, title, credits, d_id) values (317, 'Air Conditioning', 3, 7);
insert into Course (c_id, title, credits, d_id) values (318, 'TCD', 3, 11);
insert into Course (c_id, title, credits, d_id) values (319, 'Yacht Deliveries', 3, 3);
insert into Course (c_id, title, credits, d_id) values (320, 'Corporate Real Estate', 3, 4);
insert into Course (c_id, title, credits, d_id) values (321, 'Eggplant', 3, 1);
insert into Course (c_id, title, credits, d_id) values (322, 'GBA', 3, 2);
insert into Course (c_id, title, credits, d_id) values (323, 'BSP', 3, 10);
insert into Course (c_id, title, credits, d_id) values (324, 'Logo Design', 3, 1);
insert into Course (c_id, title, credits, d_id) values (325, 'NIST', 3, 3);
insert into Course (c_id, title, credits, d_id) values (326, 'Black Box Testing', 3, 10);
insert into Course (c_id, title, credits, d_id) values (327, 'CSLA', 3, 8);
insert into Course (c_id, title, credits, d_id) values (328, 'SNP genotyping', 3, 2);
insert into Course (c_id, title, credits, d_id) values (329, 'RCM', 3, 4);
insert into Course (c_id, title, credits, d_id) values (330, 'Zultys', 3, 4);
insert into Course (c_id, title, credits, d_id) values (331, 'EPR', 3, 2);
insert into Course (c_id, title, credits, d_id) values (332, 'Yarn', 3, 6);
insert into Course (c_id, title, credits, d_id) values (333, 'MVNO', 3, 8);
insert into Course (c_id, title, credits, d_id) values (334, 'Curriculum Design', 3, 7);
insert into Course (c_id, title, credits, d_id) values (335, 'Start-ups Management', 3, 12);
insert into Course (c_id, title, credits, d_id) values (336, 'XSL-FO', 3, 2);
insert into Course (c_id, title, credits, d_id) values (337, 'CCENT', 3, 11);
insert into Course (c_id, title, credits, d_id) values (338, 'RFLP', 3, 11);
insert into Course (c_id, title, credits, d_id) values (339, 'Marketing Communications', 3, 3);
insert into Course (c_id, title, credits, d_id) values (340, 'Blueprint Reading', 3, 2);
insert into Course (c_id, title, credits, d_id) values (341, 'CGEIT', 3, 3);
insert into Course (c_id, title, credits, d_id) values (342, 'RMP', 3, 9);
insert into Course (c_id, title, credits, d_id) values (343, 'VSAT', 3, 5);
insert into Course (c_id, title, credits, d_id) values (344, 'SRDS', 3, 4);
insert into Course (c_id, title, credits, d_id) values (345, 'DDMS', 3, 7);
insert into Course (c_id, title, credits, d_id) values (346, 'Sybase SQL Anywhere', 3, 8);
insert into Course (c_id, title, credits, d_id) values (347, 'XPlanner', 3, 10);
insert into Course (c_id, title, credits, d_id) values (348, 'MbUnit', 3, 12);
insert into Course (c_id, title, credits, d_id) values (349, 'Water Resources', 3, 6);
insert into Course (c_id, title, credits, d_id) values (350, 'Ehcache', 3, 11);
insert into Course (c_id, title, credits, d_id) values (351, 'Outlook Express', 3, 10);
insert into Course (c_id, title, credits, d_id) values (352, 'IDX', 3, 3);
insert into Course (c_id, title, credits, d_id) values (353, 'Avid DS Nitris', 3, 11);
insert into Course (c_id, title, credits, d_id) values (354, 'Epidemiology', 3, 4);
insert into Course (c_id, title, credits, d_id) values (355, 'Data Mining', 3, 2);
insert into Course (c_id, title, credits, d_id) values (356, 'NSI', 3, 1);
insert into Course (c_id, title, credits, d_id) values (357, 'Zeus', 3, 5);
insert into Course (c_id, title, credits, d_id) values (358, 'Product Development', 3, 7);
insert into Course (c_id, title, credits, d_id) values (359, 'Technical Documentation', 3, 5);
insert into Course (c_id, title, credits, d_id) values (360, 'Jenkins', 3, 8);
insert into Course (c_id, title, credits, d_id) values (361, 'Cisco Routers', 3, 3);
insert into Course (c_id, title, credits, d_id) values (362, 'Utility Billing', 3, 1);
insert into Course (c_id, title, credits, d_id) values (363, 'ERISA', 3, 4);
insert into Course (c_id, title, credits, d_id) values (364, 'Epigenetics', 3, 8);
insert into Course (c_id, title, credits, d_id) values (365, 'HP uCMDB', 3, 12);
insert into Course (c_id, title, credits, d_id) values (366, 'EPM', 3, 12);
insert into Course (c_id, title, credits, d_id) values (367, 'Japanese', 3, 11);
insert into Course (c_id, title, credits, d_id) values (368, 'XStream', 3, 10);
insert into Course (c_id, title, credits, d_id) values (369, 'HTK', 3, 10);
insert into Course (c_id, title, credits, d_id) values (370, 'SharePoint Server', 3, 2);
insert into Course (c_id, title, credits, d_id) values (371, 'Type 2 Diabetes', 3, 2);
insert into Course (c_id, title, credits, d_id) values (372, 'ISO 9001', 3, 8);
insert into Course (c_id, title, credits, d_id) values (373, 'MFR', 3, 3);
insert into Course (c_id, title, credits, d_id) values (374, 'Oracle E-Business Suite', 3, 11);
insert into Course (c_id, title, credits, d_id) values (375, 'Transportation', 3, 10);
insert into Course (c_id, title, credits, d_id) values (376, 'FHA', 3, 5);
insert into Course (c_id, title, credits, d_id) values (377, 'BTE', 3, 8);
insert into Course (c_id, title, credits, d_id) values (378, 'Submittals', 3, 1);
insert into Course (c_id, title, credits, d_id) values (379, 'Human Resources', 3, 10);
insert into Course (c_id, title, credits, d_id) values (380, 'Citrix', 3, 9);
insert into Course (c_id, title, credits, d_id) values (381, 'Ulead VideoStudio', 3, 3);
insert into Course (c_id, title, credits, d_id) values (382, 'SNOMED', 3, 12);
insert into Course (c_id, title, credits, d_id) values (383, 'DVB-C', 3, 11);
insert into Course (c_id, title, credits, d_id) values (384, 'Tissue Culture', 3, 5);
insert into Course (c_id, title, credits, d_id) values (385, 'Video Games', 3, 9);
insert into Course (c_id, title, credits, d_id) values (386, 'EBP', 3, 10);
insert into Course (c_id, title, credits, d_id) values (387, 'Executive Coaching', 3, 7);
insert into Course (c_id, title, credits, d_id) values (388, 'Medical Affairs', 3, 4);
insert into Course (c_id, title, credits, d_id) values (389, 'HUD', 3, 1);
insert into Course (c_id, title, credits, d_id) values (390, 'Cardiac Rhythm Management', 3, 1);
insert into Course (c_id, title, credits, d_id) values (391, 'HMC', 3, 12);
insert into Course (c_id, title, credits, d_id) values (392, 'TUPE', 3, 10);
insert into Course (c_id, title, credits, d_id) values (393, 'UHF', 3, 5);
insert into Course (c_id, title, credits, d_id) values (394, 'RDC', 3, 5);
insert into Course (c_id, title, credits, d_id) values (395, 'Slate', 3, 9);
insert into Course (c_id, title, credits, d_id) values (396, 'Microsoft Dynamics NAV', 3, 9);
insert into Course (c_id, title, credits, d_id) values (397, 'XML Standards', 3, 3);
insert into Course (c_id, title, credits, d_id) values (398, 'IEC 61131-3', 3, 12);
insert into Course (c_id, title, credits, d_id) values (399, 'Applied Kinesiology', 3, 10);
insert into Course (c_id, title, credits, d_id) values (400, 'Yellow Pages', 3, 5);
insert into Course (c_id, title, credits, d_id) values (401, 'Gx', 3, 6);
insert into Course (c_id, title, credits, d_id) values (402, 'BD+C', 3, 11);
insert into Course (c_id, title, credits, d_id) values (403, 'HR Policy Formulation', 3, 6);
insert into Course (c_id, title, credits, d_id) values (404, 'DITA XML', 3, 6);
insert into Course (c_id, title, credits, d_id) values (405, 'DFLSS', 3, 6);
insert into Course (c_id, title, credits, d_id) values (406, 'DDS', 3, 5);
insert into Course (c_id, title, credits, d_id) values (407, 'EPC', 3, 3);
insert into Course (c_id, title, credits, d_id) values (408, 'Flight Safety', 3, 6);
insert into Course (c_id, title, credits, d_id) values (409, 'Job Analysis', 3, 5);
insert into Course (c_id, title, credits, d_id) values (410, 'Blackberry', 3, 3);
insert into Course (c_id, title, credits, d_id) values (411, 'Sap Fm', 3, 1);
insert into Course (c_id, title, credits, d_id) values (412, 'Wastewater Treatment', 3, 9);
insert into Course (c_id, title, credits, d_id) values (413, 'Dell KACE', 3, 3);
insert into Course (c_id, title, credits, d_id) values (414, 'RPG', 3, 5);
insert into Course (c_id, title, credits, d_id) values (415, 'Systems Engineering', 3, 10);
insert into Course (c_id, title, credits, d_id) values (416, 'Training Delivery', 3, 12);
insert into Course (c_id, title, credits, d_id) values (417, 'Electrical Controls', 3, 3);
insert into Course (c_id, title, credits, d_id) values (418, 'Vector Illustration', 3, 7);
insert into Course (c_id, title, credits, d_id) values (419, 'BPML', 3, 12);
insert into Course (c_id, title, credits, d_id) values (420, 'Capital Markets', 3, 11);
insert into Course (c_id, title, credits, d_id) values (421, 'Drywall', 3, 8);
insert into Course (c_id, title, credits, d_id) values (422, 'TLM', 3, 4);
insert into Course (c_id, title, credits, d_id) values (423, 'Kontakt', 3, 9);
insert into Course (c_id, title, credits, d_id) values (424, 'Zinc', 3, 10);
insert into Course (c_id, title, credits, d_id) values (425, 'KRAs', 3, 11);
insert into Course (c_id, title, credits, d_id) values (426, 'Internet Yellow Pages', 3, 1);
insert into Course (c_id, title, credits, d_id) values (427, 'Oil &amp; Gas Exploration', 3, 12);
insert into Course (c_id, title, credits, d_id) values (428, 'PNF', 3, 6);
insert into Course (c_id, title, credits, d_id) values (429, 'Typesetting', 3, 11);
insert into Course (c_id, title, credits, d_id) values (430, 'Political Risk Analysis', 3, 6);
insert into Course (c_id, title, credits, d_id) values (431, 'IBM BPM', 3, 11);
insert into Course (c_id, title, credits, d_id) values (432, 'QAD', 3, 10);
insert into Course (c_id, title, credits, d_id) values (433, 'Radio Promotions', 3, 8);
insert into Course (c_id, title, credits, d_id) values (434, 'Union Avoidance', 3, 7);
insert into Course (c_id, title, credits, d_id) values (435, 'Pdf', 3, 3);
insert into Course (c_id, title, credits, d_id) values (436, 'Kernel Programming', 3, 7);
insert into Course (c_id, title, credits, d_id) values (437, 'Fashion Design', 3, 3);
insert into Course (c_id, title, credits, d_id) values (438, 'USDA Rural Housing', 3, 6);
insert into Course (c_id, title, credits, d_id) values (439, 'CST Microwave Studio', 3, 4);
insert into Course (c_id, title, credits, d_id) values (440, 'Iyengar Yoga', 3, 4);
insert into Course (c_id, title, credits, d_id) values (441, 'IXIA', 3, 4);
insert into Course (c_id, title, credits, d_id) values (442, 'Notary Public', 3, 6);
insert into Course (c_id, title, credits, d_id) values (443, 'CMS', 3, 12);
insert into Course (c_id, title, credits, d_id) values (444, 'VxWorks', 3, 6);
insert into Course (c_id, title, credits, d_id) values (445, 'RTU', 3, 2);
insert into Course (c_id, title, credits, d_id) values (446, 'XSLT', 3, 4);
insert into Course (c_id, title, credits, d_id) values (447, 'ESRI', 3, 10);
insert into Course (c_id, title, credits, d_id) values (448, 'AED', 3, 6);
insert into Course (c_id, title, credits, d_id) values (449, 'TMS320', 3, 12);
insert into Course (c_id, title, credits, d_id) values (450, 'MMIC', 3, 12);
insert into Course (c_id, title, credits, d_id) values (451, 'FBCB2', 3, 5);
insert into Course (c_id, title, credits, d_id) values (452, 'FX Swaps', 3, 7);
insert into Course (c_id, title, credits, d_id) values (453, 'Wind', 3, 9);
insert into Course (c_id, title, credits, d_id) values (454, 'PPC', 3, 2);
insert into Course (c_id, title, credits, d_id) values (455, 'CD packaging', 3, 7);
insert into Course (c_id, title, credits, d_id) values (456, 'Axure RP', 3, 2);
insert into Course (c_id, title, credits, d_id) values (457, 'Web Analytics', 3, 9);
insert into Course (c_id, title, credits, d_id) values (458, 'NCMR', 3, 11);
insert into Course (c_id, title, credits, d_id) values (459, 'Gypsum', 3, 2);
insert into Course (c_id, title, credits, d_id) values (460, 'Time &amp; Attendance', 3, 7);
insert into Course (c_id, title, credits, d_id) values (461, 'Aircraft Maintenance', 3, 7);
insert into Course (c_id, title, credits, d_id) values (462, 'NYMEX', 3, 12);
insert into Course (c_id, title, credits, d_id) values (463, 'KDB+', 3, 1);
insert into Course (c_id, title, credits, d_id) values (464, 'Access Control', 3, 12);
insert into Course (c_id, title, credits, d_id) values (465, 'OEM contracts', 3, 7);
insert into Course (c_id, title, credits, d_id) values (466, 'NPL', 3, 2);
insert into Course (c_id, title, credits, d_id) values (467, 'TWiki', 3, 9);
insert into Course (c_id, title, credits, d_id) values (468, 'Vendor Relations', 3, 9);
insert into Course (c_id, title, credits, d_id) values (469, 'XML Standards', 3, 1);
insert into Course (c_id, title, credits, d_id) values (470, 'FMV', 3, 1);
insert into Course (c_id, title, credits, d_id) values (471, 'SMT', 3, 12);
insert into Course (c_id, title, credits, d_id) values (472, 'Embedded Software', 3, 5);
insert into Course (c_id, title, credits, d_id) values (473, 'ETABS', 3, 6);
insert into Course (c_id, title, credits, d_id) values (474, 'Risk Assessment', 3, 2);
insert into Course (c_id, title, credits, d_id) values (475, 'Cash Management', 3, 11);
insert into Course (c_id, title, credits, d_id) values (476, 'Windows', 3, 12);
insert into Course (c_id, title, credits, d_id) values (477, 'MRO Management', 3, 10);
insert into Course (c_id, title, credits, d_id) values (478, 'BBP', 3, 1);
insert into Course (c_id, title, credits, d_id) values (479, 'PCRF', 3, 3);
insert into Course (c_id, title, credits, d_id) values (480, 'Pygame', 3, 3);
insert into Course (c_id, title, credits, d_id) values (481, 'FMV', 3, 1);
insert into Course (c_id, title, credits, d_id) values (482, 'Airline Ticketing', 3, 9);
insert into Course (c_id, title, credits, d_id) values (483, 'QS1', 3, 5);
insert into Course (c_id, title, credits, d_id) values (484, 'FDDI', 3, 11);
insert into Course (c_id, title, credits, d_id) values (485, 'High Sense Of Urgency', 3, 4);
insert into Course (c_id, title, credits, d_id) values (486, 'DSDM', 3, 3);
insert into Course (c_id, title, credits, d_id) values (487, 'LabWindows/CVI', 3, 6);
insert into Course (c_id, title, credits, d_id) values (488, 'JIT', 3, 3);
insert into Course (c_id, title, credits, d_id) values (489, 'GMAT', 3, 10);
insert into Course (c_id, title, credits, d_id) values (490, 'Zeolites', 3, 11);
insert into Course (c_id, title, credits, d_id) values (491, 'Drama', 3, 9);
insert into Course (c_id, title, credits, d_id) values (492, 'IO', 3, 9);
insert into Course (c_id, title, credits, d_id) values (493, 'Euroclear', 3, 3);
insert into Course (c_id, title, credits, d_id) values (494, 'CI', 3, 11);
insert into Course (c_id, title, credits, d_id) values (495, 'VB.NET', 3, 6);
insert into Course (c_id, title, credits, d_id) values (496, 'JSA', 3, 10);
insert into Course (c_id, title, credits, d_id) values (497, 'Oracle XE', 3, 2);
insert into Course (c_id, title, credits, d_id) values (498, 'JGroups', 3, 10);
insert into Course (c_id, title, credits, d_id) values (499, 'Routing', 3, 1);
insert into Course (c_id, title, credits, d_id) values (500, 'Zebra', 3, 11);
insert into Course (c_id, title, credits, d_id) values (501, 'LSS', 3, 3);
insert into Course (c_id, title, credits, d_id) values (502, 'European Affairs', 3, 3);
insert into Course (c_id, title, credits, d_id) values (503, 'TCP', 3, 1);
insert into Course (c_id, title, credits, d_id) values (504, 'PLC Allen Bradley', 3, 2);
insert into Course (c_id, title, credits, d_id) values (505, 'Dell KACE', 3, 9);
insert into Course (c_id, title, credits, d_id) values (506, 'IBC', 3, 3);
insert into Course (c_id, title, credits, d_id) values (507, 'IxChariot', 3, 1);
insert into Course (c_id, title, credits, d_id) values (508, 'HP Quality Center', 3, 10);
insert into Course (c_id, title, credits, d_id) values (509, 'UF/DF', 3, 9);
insert into Course (c_id, title, credits, d_id) values (510, 'Tween', 3, 1);
insert into Course (c_id, title, credits, d_id) values (511, 'MPLS', 3, 6);
insert into Course (c_id, title, credits, d_id) values (512, 'Corporate Gifts', 3, 2);
insert into Course (c_id, title, credits, d_id) values (513, 'FpML', 3, 10);
insert into Course (c_id, title, credits, d_id) values (514, 'APO SNP', 3, 9);
insert into Course (c_id, title, credits, d_id) values (515, 'Omron', 3, 3);
insert into Course (c_id, title, credits, d_id) values (516, 'RSA Ace Server', 3, 2);
insert into Course (c_id, title, credits, d_id) values (517, 'Java RMI', 3, 11);
insert into Course (c_id, title, credits, d_id) values (518, 'Substance Use Disorders', 3, 9);
insert into Course (c_id, title, credits, d_id) values (519, 'Asset Management', 3, 5);
insert into Course (c_id, title, credits, d_id) values (520, 'Radio Host', 3, 3);
insert into Course (c_id, title, credits, d_id) values (521, 'Kyphoplasty', 3, 1);
insert into Course (c_id, title, credits, d_id) values (522, 'Lotus Notes', 3, 12);
insert into Course (c_id, title, credits, d_id) values (523, 'Flex', 3, 7);
insert into Course (c_id, title, credits, d_id) values (524, 'Flow Cytometry', 3, 4);
insert into Course (c_id, title, credits, d_id) values (525, 'MPBGP', 3, 7);
insert into Course (c_id, title, credits, d_id) values (526, 'Award Ceremonies', 3, 1);
insert into Course (c_id, title, credits, d_id) values (527, 'Mac OS', 3, 5);
insert into Course (c_id, title, credits, d_id) values (528, 'Electricians', 3, 8);
insert into Course (c_id, title, credits, d_id) values (529, 'Trade Marketing', 3, 3);
insert into Course (c_id, title, credits, d_id) values (530, 'OLT', 3, 4);
insert into Course (c_id, title, credits, d_id) values (531, 'PFS', 3, 2);
insert into Course (c_id, title, credits, d_id) values (532, 'Youth Empowerment', 3, 10);
insert into Course (c_id, title, credits, d_id) values (533, 'Pivot Tables', 3, 8);
insert into Course (c_id, title, credits, d_id) values (534, 'Medical Nutrition Therapy', 3, 10);
insert into Course (c_id, title, credits, d_id) values (535, 'Overcoming Challenges', 3, 9);
insert into Course (c_id, title, credits, d_id) values (536, 'UV Mapping', 3, 11);
insert into Course (c_id, title, credits, d_id) values (537, 'PFlow', 3, 7);
insert into Course (c_id, title, credits, d_id) values (538, 'Urinalysis', 3, 4);
insert into Course (c_id, title, credits, d_id) values (539, 'Axis', 3, 10);
insert into Course (c_id, title, credits, d_id) values (540, 'UCITS', 3, 11);
insert into Course (c_id, title, credits, d_id) values (541, 'e-QIP', 3, 9);
insert into Course (c_id, title, credits, d_id) values (542, 'JCIDS', 3, 3);
insert into Course (c_id, title, credits, d_id) values (543, 'Pyxis', 3, 5);
insert into Course (c_id, title, credits, d_id) values (544, 'RFP Design', 3, 8);
insert into Course (c_id, title, credits, d_id) values (545, 'Healthcare Industry', 3, 9);
insert into Course (c_id, title, credits, d_id) values (546, 'VMware ESX', 3, 11);
insert into Course (c_id, title, credits, d_id) values (547, 'CMA', 3, 10);
insert into Course (c_id, title, credits, d_id) values (548, 'NLTK', 3, 2);
insert into Course (c_id, title, credits, d_id) values (549, 'Segregation of Duties', 3, 9);
insert into Course (c_id, title, credits, d_id) values (550, 'Hazard Recognition', 3, 11);
insert into Course (c_id, title, credits, d_id) values (551, 'CTP', 3, 7);
insert into Course (c_id, title, credits, d_id) values (552, 'System Testing', 3, 3);
insert into Course (c_id, title, credits, d_id) values (553, 'Oligonucleotide Synthesis', 3, 7);
insert into Course (c_id, title, credits, d_id) values (554, 'QA Automation', 3, 4);
insert into Course (c_id, title, credits, d_id) values (555, 'GFP', 3, 2);
insert into Course (c_id, title, credits, d_id) values (556, 'cDNA', 3, 2);
insert into Course (c_id, title, credits, d_id) values (557, 'ISO 14001', 3, 9);
insert into Course (c_id, title, credits, d_id) values (558, 'Knowledge Management', 3, 10);
insert into Course (c_id, title, credits, d_id) values (559, 'Numerical Ability', 3, 9);
insert into Course (c_id, title, credits, d_id) values (560, 'DCL', 3, 2);
insert into Course (c_id, title, credits, d_id) values (561, 'Turn Around Management', 3, 8);
insert into Course (c_id, title, credits, d_id) values (562, 'TBS', 3, 11);
insert into Course (c_id, title, credits, d_id) values (563, 'JBuilder', 3, 2);
insert into Course (c_id, title, credits, d_id) values (564, 'Organizational Effectiveness', 3, 7);
insert into Course (c_id, title, credits, d_id) values (565, 'NMS', 3, 6);
insert into Course (c_id, title, credits, d_id) values (566, 'JPAS', 3, 8);
insert into Course (c_id, title, credits, d_id) values (567, 'OGRE', 3, 6);
insert into Course (c_id, title, credits, d_id) values (568, 'FX Swaps', 3, 7);
insert into Course (c_id, title, credits, d_id) values (569, 'Economic Development', 3, 6);
insert into Course (c_id, title, credits, d_id) values (570, 'Emergency Medicine', 3, 4);
insert into Course (c_id, title, credits, d_id) values (571, 'Aftersales', 3, 1);
insert into Course (c_id, title, credits, d_id) values (572, 'WFL', 3, 2);
insert into Course (c_id, title, credits, d_id) values (573, 'VSX', 3, 11);
insert into Course (c_id, title, credits, d_id) values (574, 'HR Strategy', 3, 2);
insert into Course (c_id, title, credits, d_id) values (575, 'Management by Objectives', 3, 1);
insert into Course (c_id, title, credits, d_id) values (576, 'Vulcan', 3, 2);
insert into Course (c_id, title, credits, d_id) values (577, 'Komodo Edit', 3, 6);
insert into Course (c_id, title, credits, d_id) values (578, 'Guardianship', 3, 11);
insert into Course (c_id, title, credits, d_id) values (579, 'User Experience Design', 3, 8);
insert into Course (c_id, title, credits, d_id) values (580, 'GIS systems', 3, 6);
insert into Course (c_id, title, credits, d_id) values (581, 'Revenue Cycle', 3, 9);
insert into Course (c_id, title, credits, d_id) values (582, 'Data Quality', 3, 10);
insert into Course (c_id, title, credits, d_id) values (583, 'BGP', 3, 8);
insert into Course (c_id, title, credits, d_id) values (584, 'Application Architecture', 3, 12);
insert into Course (c_id, title, credits, d_id) values (585, 'Flatbed', 3, 7);
insert into Course (c_id, title, credits, d_id) values (586, 'Jury Trials', 3, 4);
insert into Course (c_id, title, credits, d_id) values (587, 'Payment by Results', 3, 10);
insert into Course (c_id, title, credits, d_id) values (588, 'Appeals', 3, 8);
insert into Course (c_id, title, credits, d_id) values (589, 'DG Sets', 3, 6);
insert into Course (c_id, title, credits, d_id) values (590, 'VMI Programs', 3, 4);
insert into Course (c_id, title, credits, d_id) values (591, 'CT Summation', 3, 9);
insert into Course (c_id, title, credits, d_id) values (592, 'MVC Architecture', 3, 8);
insert into Course (c_id, title, credits, d_id) values (593, 'Hospital Sales', 3, 8);
insert into Course (c_id, title, credits, d_id) values (594, 'CVS', 3, 1);
insert into Course (c_id, title, credits, d_id) values (595, 'Database Design', 3, 4);
insert into Course (c_id, title, credits, d_id) values (596, 'Rsync', 3, 4);
insert into Course (c_id, title, credits, d_id) values (597, 'XP/Vista/7', 3, 3);
insert into Course (c_id, title, credits, d_id) values (598, 'Project Bidding', 3, 8);
insert into Course (c_id, title, credits, d_id) values (599, 'Watercolor', 3, 6);
insert into Course (c_id, title, credits, d_id) values (600, 'CWTS', 3, 3);
insert into Course (c_id, title, credits, d_id) values (601, 'PK/PD', 3, 10);
insert into Course (c_id, title, credits, d_id) values (602, 'KVM', 3, 4);
insert into Course (c_id, title, credits, d_id) values (603, 'Group Dynamics', 3, 3);
insert into Course (c_id, title, credits, d_id) values (604, 'EKG', 3, 9);
insert into Course (c_id, title, credits, d_id) values (605, 'GNU Debugger', 3, 12);
insert into Course (c_id, title, credits, d_id) values (606, 'Gourmet', 3, 12);
insert into Course (c_id, title, credits, d_id) values (607, 'Eblasts', 3, 10);
insert into Course (c_id, title, credits, d_id) values (608, 'Work Effectively', 3, 10);
insert into Course (c_id, title, credits, d_id) values (609, 'Employee Engagement', 3, 1);
insert into Course (c_id, title, credits, d_id) values (610, 'Xplan', 3, 2);
insert into Course (c_id, title, credits, d_id) values (611, 'LAN Switching', 3, 2);
insert into Course (c_id, title, credits, d_id) values (612, 'DFSS Green Belt', 3, 9);
insert into Course (c_id, title, credits, d_id) values (613, 'LGBT Rights', 3, 1);
insert into Course (c_id, title, credits, d_id) values (614, 'Professional Liability', 3, 1);
insert into Course (c_id, title, credits, d_id) values (615, 'WFL', 3, 8);
insert into Course (c_id, title, credits, d_id) values (616, 'Social Justice', 3, 1);
insert into Course (c_id, title, credits, d_id) values (617, 'Olfaction', 3, 12);
insert into Course (c_id, title, credits, d_id) values (618, 'WSE', 3, 12);
insert into Course (c_id, title, credits, d_id) values (619, 'GSM', 3, 6);
insert into Course (c_id, title, credits, d_id) values (620, 'German', 3, 11);
insert into Course (c_id, title, credits, d_id) values (621, 'HCSS', 3, 10);
insert into Course (c_id, title, credits, d_id) values (622, 'Small Business', 3, 5);
insert into Course (c_id, title, credits, d_id) values (623, 'QS9000', 3, 10);
insert into Course (c_id, title, credits, d_id) values (624, 'BMC Remedy AR System', 3, 5);
insert into Course (c_id, title, credits, d_id) values (625, 'BBEdit', 3, 1);
insert into Course (c_id, title, credits, d_id) values (626, 'Family Law', 3, 12);
insert into Course (c_id, title, credits, d_id) values (627, 'AACR2', 3, 6);
insert into Course (c_id, title, credits, d_id) values (628, 'Tiles', 3, 5);
insert into Course (c_id, title, credits, d_id) values (629, 'Litigation', 3, 7);
insert into Course (c_id, title, credits, d_id) values (630, 'DVD Duplication', 3, 1);
insert into Course (c_id, title, credits, d_id) values (631, 'NDT', 3, 12);
insert into Course (c_id, title, credits, d_id) values (632, 'Image Processing', 3, 1);
insert into Course (c_id, title, credits, d_id) values (633, 'WTT', 3, 8);
insert into Course (c_id, title, credits, d_id) values (634, 'OGC Gateway Reviews', 3, 9);
insert into Course (c_id, title, credits, d_id) values (635, 'Hyperion HFM', 3, 1);
insert into Course (c_id, title, credits, d_id) values (636, 'RSVP-TE', 3, 4);
insert into Course (c_id, title, credits, d_id) values (637, 'IM', 3, 9);
insert into Course (c_id, title, credits, d_id) values (638, 'RNAi', 3, 11);
insert into Course (c_id, title, credits, d_id) values (639, 'SVT', 3, 10);
insert into Course (c_id, title, credits, d_id) values (640, 'RMS', 3, 1);
insert into Course (c_id, title, credits, d_id) values (641, 'CPFR', 3, 5);
insert into Course (c_id, title, credits, d_id) values (642, 'RFQ', 3, 1);
insert into Course (c_id, title, credits, d_id) values (643, 'Ion Exchange', 3, 9);
insert into Course (c_id, title, credits, d_id) values (644, 'Oasys', 3, 7);
insert into Course (c_id, title, credits, d_id) values (645, 'RPOs', 3, 4);
insert into Course (c_id, title, credits, d_id) values (646, 'KWI', 3, 4);
insert into Course (c_id, title, credits, d_id) values (647, 'DLL', 3, 5);
insert into Course (c_id, title, credits, d_id) values (648, 'Lyra', 3, 1);
insert into Course (c_id, title, credits, d_id) values (649, '.htaccess', 3, 2);
insert into Course (c_id, title, credits, d_id) values (650, 'Airworthiness', 3, 7);
insert into Course (c_id, title, credits, d_id) values (651, 'EHS', 3, 11);
insert into Course (c_id, title, credits, d_id) values (652, 'SRT', 3, 5);
insert into Course (c_id, title, credits, d_id) values (653, 'Servers', 3, 10);
insert into Course (c_id, title, credits, d_id) values (654, 'XMPP', 3, 10);
insert into Course (c_id, title, credits, d_id) values (655, 'SGSN', 3, 10);
insert into Course (c_id, title, credits, d_id) values (656, 'Nuke', 3, 11);
insert into Course (c_id, title, credits, d_id) values (657, 'NX Unigraphics', 3, 2);
insert into Course (c_id, title, credits, d_id) values (658, 'Following Up', 3, 6);
insert into Course (c_id, title, credits, d_id) values (659, 'Student Financial Aid', 3, 1);
insert into Course (c_id, title, credits, d_id) values (660, 'Ruby on Rails', 3, 3);
insert into Course (c_id, title, credits, d_id) values (661, 'SBR', 3, 6);
insert into Course (c_id, title, credits, d_id) values (662, 'Bass Guitar', 3, 10);
insert into Course (c_id, title, credits, d_id) values (663, 'DTMF', 3, 11);
insert into Course (c_id, title, credits, d_id) values (664, 'GPP', 3, 7);
insert into Course (c_id, title, credits, d_id) values (665, 'LNA', 3, 9);
insert into Course (c_id, title, credits, d_id) values (666, 'OMB A-123', 3, 8);
insert into Course (c_id, title, credits, d_id) values (667, 'Powers of Attorney', 3, 1);
insert into Course (c_id, title, credits, d_id) values (668, 'NLRB', 3, 7);
insert into Course (c_id, title, credits, d_id) values (669, 'PK', 3, 11);
insert into Course (c_id, title, credits, d_id) values (670, 'Sports Nutrition', 3, 2);
insert into Course (c_id, title, credits, d_id) values (671, 'BMC Remedy Administration', 3, 8);
insert into Course (c_id, title, credits, d_id) values (672, 'Medicare', 3, 9);
insert into Course (c_id, title, credits, d_id) values (673, 'Digital Signage', 3, 2);
insert into Course (c_id, title, credits, d_id) values (674, 'Spectroscopy', 3, 10);
insert into Course (c_id, title, credits, d_id) values (675, 'MBOX', 3, 4);
insert into Course (c_id, title, credits, d_id) values (676, 'RF Test', 3, 11);
insert into Course (c_id, title, credits, d_id) values (677, 'Gold', 3, 6);
insert into Course (c_id, title, credits, d_id) values (678, 'Sybase SQL Anywhere', 3, 8);
insert into Course (c_id, title, credits, d_id) values (679, 'Business Objects Data Integrator', 3, 1);
insert into Course (c_id, title, credits, d_id) values (680, 'Ice Cream', 3, 11);
insert into Course (c_id, title, credits, d_id) values (681, 'Cuisine', 3, 10);
insert into Course (c_id, title, credits, d_id) values (682, 'WDF', 3, 3);
insert into Course (c_id, title, credits, d_id) values (683, 'ELISA', 3, 3);
insert into Course (c_id, title, credits, d_id) values (684, 'Organizational Development', 3, 11);
insert into Course (c_id, title, credits, d_id) values (685, 'VMS', 3, 12);
insert into Course (c_id, title, credits, d_id) values (686, 'Water', 3, 4);
insert into Course (c_id, title, credits, d_id) values (687, 'HR Consulting', 3, 3);
insert into Course (c_id, title, credits, d_id) values (688, 'DXL', 3, 9);
insert into Course (c_id, title, credits, d_id) values (689, 'Entrepreneurship', 3, 8);
insert into Course (c_id, title, credits, d_id) values (690, 'Brocade Fibre Switches', 3, 9);
insert into Course (c_id, title, credits, d_id) values (691, 'Alarm Systems', 3, 12);
insert into Course (c_id, title, credits, d_id) values (692, 'Lyophilization', 3, 5);
insert into Course (c_id, title, credits, d_id) values (693, 'MXP', 3, 6);
insert into Course (c_id, title, credits, d_id) values (694, 'EEO Compliance', 3, 12);
insert into Course (c_id, title, credits, d_id) values (695, 'Amazon RDS', 3, 12);
insert into Course (c_id, title, credits, d_id) values (696, 'GPS', 3, 2);
insert into Course (c_id, title, credits, d_id) values (697, 'CNOR', 3, 1);
insert into Course (c_id, title, credits, d_id) values (698, 'Embedded Linux', 3, 10);
insert into Course (c_id, title, credits, d_id) values (699, 'Kantar', 3, 11);
insert into Course (c_id, title, credits, d_id) values (700, 'Oxidative Stress', 3, 5);
insert into Course (c_id, title, credits, d_id) values (701, 'CMMS', 3, 8);
insert into Course (c_id, title, credits, d_id) values (702, 'Phase II', 3, 5);
insert into Course (c_id, title, credits, d_id) values (703, 'Illustrator', 3, 1);
insert into Course (c_id, title, credits, d_id) values (704, 'Wheat', 3, 11);
insert into Course (c_id, title, credits, d_id) values (705, 'Dry Eye', 3, 2);
insert into Course (c_id, title, credits, d_id) values (706, 'IABP', 3, 11);
insert into Course (c_id, title, credits, d_id) values (707, 'Integrated Circuit Design', 3, 6);
insert into Course (c_id, title, credits, d_id) values (708, 'High Performance Computing', 3, 7);
insert into Course (c_id, title, credits, d_id) values (709, 'FSMS', 3, 9);
insert into Course (c_id, title, credits, d_id) values (710, 'OATS', 3, 8);
insert into Course (c_id, title, credits, d_id) values (711, 'Automotive Aftermarket', 3, 8);
insert into Course (c_id, title, credits, d_id) values (712, 'PNF', 3, 3);
insert into Course (c_id, title, credits, d_id) values (713, 'GNU Octave', 3, 4);
insert into Course (c_id, title, credits, d_id) values (714, '.htaccess', 3, 1);
insert into Course (c_id, title, credits, d_id) values (715, 'Flight Planning', 3, 3);
insert into Course (c_id, title, credits, d_id) values (716, 'CSG', 3, 8);
insert into Course (c_id, title, credits, d_id) values (717, 'Organization Skills', 3, 1);
insert into Course (c_id, title, credits, d_id) values (718, 'Egyptian Arabic', 3, 5);
insert into Course (c_id, title, credits, d_id) values (719, 'Policy Writing', 3, 12);
insert into Course (c_id, title, credits, d_id) values (720, 'Core Java', 3, 6);
insert into Course (c_id, title, credits, d_id) values (721, 'At-risk', 3, 1);
insert into Course (c_id, title, credits, d_id) values (722, 'BBQ', 3, 6);
insert into Course (c_id, title, credits, d_id) values (723, 'Tactics', 3, 8);
insert into Course (c_id, title, credits, d_id) values (724, 'OEM Management', 3, 11);
insert into Course (c_id, title, credits, d_id) values (725, 'Abaqus', 3, 12);
insert into Course (c_id, title, credits, d_id) values (726, 'Digital Journalism', 3, 9);
insert into Course (c_id, title, credits, d_id) values (727, 'HV', 3, 12);
insert into Course (c_id, title, credits, d_id) values (728, 'Microbiology', 3, 10);
insert into Course (c_id, title, credits, d_id) values (729, 'LCD', 3, 7);
insert into Course (c_id, title, credits, d_id) values (730, 'E-commerce', 3, 12);
insert into Course (c_id, title, credits, d_id) values (731, 'Kundalini Yoga', 3, 7);
insert into Course (c_id, title, credits, d_id) values (732, 'QinQ', 3, 6);
insert into Course (c_id, title, credits, d_id) values (733, 'Electrical Troubleshooting', 3, 1);
insert into Course (c_id, title, credits, d_id) values (734, 'NVQs', 3, 7);
insert into Course (c_id, title, credits, d_id) values (735, 'DDA compliance', 3, 3);
insert into Course (c_id, title, credits, d_id) values (736, 'Buyer Representation', 3, 3);
insert into Course (c_id, title, credits, d_id) values (737, 'P&amp;ID', 3, 1);
insert into Course (c_id, title, credits, d_id) values (738, 'Oracle OLAP', 3, 2);
insert into Course (c_id, title, credits, d_id) values (739, 'Omeka', 3, 5);
insert into Course (c_id, title, credits, d_id) values (740, 'nCloth', 3, 1);
insert into Course (c_id, title, credits, d_id) values (741, 'IP Cameras', 3, 6);
insert into Course (c_id, title, credits, d_id) values (742, 'IEEE 802.11', 3, 7);
insert into Course (c_id, title, credits, d_id) values (743, 'Federal Government', 3, 1);
insert into Course (c_id, title, credits, d_id) values (744, 'Slogans', 3, 10);
insert into Course (c_id, title, credits, d_id) values (745, 'RC Detailing', 3, 6);
insert into Course (c_id, title, credits, d_id) values (746, 'RMA', 3, 7);
insert into Course (c_id, title, credits, d_id) values (747, 'Japanese to English', 3, 3);
insert into Course (c_id, title, credits, d_id) values (748, 'Volunteering', 3, 12);
insert into Course (c_id, title, credits, d_id) values (749, 'NCAA Compliance', 3, 1);
insert into Course (c_id, title, credits, d_id) values (750, 'QEMU', 3, 11);
insert into Course (c_id, title, credits, d_id) values (751, 'SSOP', 3, 2);
insert into Course (c_id, title, credits, d_id) values (752, 'Static Timing Analysis', 3, 2);
insert into Course (c_id, title, credits, d_id) values (753, 'Employer Branding', 3, 8);
insert into Course (c_id, title, credits, d_id) values (754, '.htaccess', 3, 7);
insert into Course (c_id, title, credits, d_id) values (755, 'Guardianship', 3, 5);
insert into Course (c_id, title, credits, d_id) values (756, 'HSR', 3, 5);
insert into Course (c_id, title, credits, d_id) values (757, 'Economic Research', 3, 3);
insert into Course (c_id, title, credits, d_id) values (758, 'HMIs', 3, 8);
insert into Course (c_id, title, credits, d_id) values (759, 'Hyperion', 3, 10);
insert into Course (c_id, title, credits, d_id) values (760, 'JRuby', 3, 10);
insert into Course (c_id, title, credits, d_id) values (761, 'RPD', 3, 8);
insert into Course (c_id, title, credits, d_id) values (762, 'MW', 3, 10);
insert into Course (c_id, title, credits, d_id) values (763, 'TFTP', 3, 8);
insert into Course (c_id, title, credits, d_id) values (764, 'Sports Nutrition', 3, 11);
insert into Course (c_id, title, credits, d_id) values (765, 'JUnit', 3, 8);
insert into Course (c_id, title, credits, d_id) values (766, 'Broadband', 3, 10);
insert into Course (c_id, title, credits, d_id) values (767, 'Siebel', 3, 7);
insert into Course (c_id, title, credits, d_id) values (768, 'BTLS', 3, 10);
insert into Course (c_id, title, credits, d_id) values (769, 'PVElite', 3, 7);
insert into Course (c_id, title, credits, d_id) values (770, 'Social Media Blogging', 3, 9);
insert into Course (c_id, title, credits, d_id) values (771, 'Keyboard Skills', 3, 7);
insert into Course (c_id, title, credits, d_id) values (772, 'Site Planning', 3, 1);
insert into Course (c_id, title, credits, d_id) values (773, 'Pinterest', 3, 4);
insert into Course (c_id, title, credits, d_id) values (774, 'ISDN', 3, 12);
insert into Course (c_id, title, credits, d_id) values (775, 'Bylined Articles', 3, 4);
insert into Course (c_id, title, credits, d_id) values (776, 'Aircraft Maintenance', 3, 3);
insert into Course (c_id, title, credits, d_id) values (777, 'Vocal Coaching', 3, 7);
insert into Course (c_id, title, credits, d_id) values (778, 'Classical Guitar', 3, 11);
insert into Course (c_id, title, credits, d_id) values (779, 'HR Project Management', 3, 5);
insert into Course (c_id, title, credits, d_id) values (780, 'Overseas Sourcing', 3, 6);
insert into Course (c_id, title, credits, d_id) values (781, 'BS25999', 3, 6);
insert into Course (c_id, title, credits, d_id) values (782, 'OS X', 3, 6);
insert into Course (c_id, title, credits, d_id) values (783, 'XCAL', 3, 7);
insert into Course (c_id, title, credits, d_id) values (784, 'WTX', 3, 9);
insert into Course (c_id, title, credits, d_id) values (785, 'CSAT', 3, 10);
insert into Course (c_id, title, credits, d_id) values (786, 'Business Development', 3, 6);
insert into Course (c_id, title, credits, d_id) values (787, 'FCIP', 3, 11);
insert into Course (c_id, title, credits, d_id) values (788, 'UPS Shipping', 3, 5);
insert into Course (c_id, title, credits, d_id) values (789, 'Hearings', 3, 12);
insert into Course (c_id, title, credits, d_id) values (790, 'Flame AA', 3, 12);
insert into Course (c_id, title, credits, d_id) values (791, 'Sh', 3, 9);
insert into Course (c_id, title, credits, d_id) values (792, 'Music Festivals', 3, 9);
insert into Course (c_id, title, credits, d_id) values (793, 'Retail Banking', 3, 1);
insert into Course (c_id, title, credits, d_id) values (794, 'Geology', 3, 12);
insert into Course (c_id, title, credits, d_id) values (795, 'TCR', 3, 4);
insert into Course (c_id, title, credits, d_id) values (796, 'Lines Of Credit', 3, 1);
insert into Course (c_id, title, credits, d_id) values (797, 'Kosher', 3, 8);
insert into Course (c_id, title, credits, d_id) values (798, 'Oracle ERP', 3, 8);
insert into Course (c_id, title, credits, d_id) values (799, 'RFID+', 3, 6);
insert into Course (c_id, title, credits, d_id) values (800, 'Vendor Relations', 3, 7);
insert into Course (c_id, title, credits, d_id) values (801, 'Humanitarian', 3, 3);
insert into Course (c_id, title, credits, d_id) values (802, 'VSX', 3, 12);
insert into Course (c_id, title, credits, d_id) values (803, 'Luxury Travel', 3, 2);
insert into Course (c_id, title, credits, d_id) values (804, 'Financial Risk', 3, 6);
insert into Course (c_id, title, credits, d_id) values (805, 'LR', 3, 12);
insert into Course (c_id, title, credits, d_id) values (806, 'JIS', 3, 3);
insert into Course (c_id, title, credits, d_id) values (807, 'CBD', 3, 8);
insert into Course (c_id, title, credits, d_id) values (808, 'EBA', 3, 5);
insert into Course (c_id, title, credits, d_id) values (809, 'EIS', 3, 4);
insert into Course (c_id, title, credits, d_id) values (810, 'Electric Utility', 3, 10);
insert into Course (c_id, title, credits, d_id) values (811, 'Leadership', 3, 6);
insert into Course (c_id, title, credits, d_id) values (812, 'Sales Process', 3, 6);
insert into Course (c_id, title, credits, d_id) values (813, 'TCP', 3, 10);
insert into Course (c_id, title, credits, d_id) values (814, 'RTDS', 3, 11);
insert into Course (c_id, title, credits, d_id) values (815, 'GCIA', 3, 1);
insert into Course (c_id, title, credits, d_id) values (816, 'CSG', 3, 10);
insert into Course (c_id, title, credits, d_id) values (817, 'AKTA', 3, 9);
insert into Course (c_id, title, credits, d_id) values (818, 'Ektron', 3, 12);
insert into Course (c_id, title, credits, d_id) values (819, 'CNC Machine', 3, 2);
insert into Course (c_id, title, credits, d_id) values (820, 'LLQP', 3, 12);
insert into Course (c_id, title, credits, d_id) values (821, 'VMware VTSP', 3, 6);
insert into Course (c_id, title, credits, d_id) values (822, 'CCNP Security', 3, 12);
insert into Course (c_id, title, credits, d_id) values (823, 'Utility Locating', 3, 9);
insert into Course (c_id, title, credits, d_id) values (824, 'GIS systems', 3, 3);
insert into Course (c_id, title, credits, d_id) values (825, 'Yacht Deliveries', 3, 4);
insert into Course (c_id, title, credits, d_id) values (826, 'Training Delivery', 3, 5);
insert into Course (c_id, title, credits, d_id) values (827, 'Brazilian Jiu-Jitsu', 3, 3);
insert into Course (c_id, title, credits, d_id) values (828, 'TCF', 3, 8);
insert into Course (c_id, title, credits, d_id) values (829, 'Sales Cycle Management', 3, 7);
insert into Course (c_id, title, credits, d_id) values (830, 'Molecular Biology', 3, 4);
insert into Course (c_id, title, credits, d_id) values (831, 'Sports Management', 3, 9);
insert into Course (c_id, title, credits, d_id) values (832, 'HR Policy Formulation', 3, 11);
insert into Course (c_id, title, credits, d_id) values (833, 'MDL', 3, 6);
insert into Course (c_id, title, credits, d_id) values (834, 'WHMIS', 3, 7);
insert into Course (c_id, title, credits, d_id) values (835, 'PMP', 3, 4);
insert into Course (c_id, title, credits, d_id) values (836, 'Gaming Industry', 3, 4);
insert into Course (c_id, title, credits, d_id) values (837, 'Shell Scripting', 3, 8);
insert into Course (c_id, title, credits, d_id) values (838, 'System Architecture', 3, 8);
insert into Course (c_id, title, credits, d_id) values (839, 'VSTS', 3, 1);
insert into Course (c_id, title, credits, d_id) values (840, 'Kaizen Leadership', 3, 11);
insert into Course (c_id, title, credits, d_id) values (841, 'CPP', 3, 6);
insert into Course (c_id, title, credits, d_id) values (842, 'VMware Certified Professional', 3, 12);
insert into Course (c_id, title, credits, d_id) values (843, 'IBS', 3, 9);
insert into Course (c_id, title, credits, d_id) values (844, 'MP2', 3, 3);
insert into Course (c_id, title, credits, d_id) values (845, 'MPI', 3, 3);
insert into Course (c_id, title, credits, d_id) values (846, 'NLTK', 3, 3);
insert into Course (c_id, title, credits, d_id) values (847, 'BMC Remedy User', 3, 8);
insert into Course (c_id, title, credits, d_id) values (848, 'Current Affairs', 3, 11);
insert into Course (c_id, title, credits, d_id) values (849, 'Dump Truck', 3, 11);
insert into Course (c_id, title, credits, d_id) values (850, 'PBASIC', 3, 6);
insert into Course (c_id, title, credits, d_id) values (851, 'Warehouse Management', 3, 2);
insert into Course (c_id, title, credits, d_id) values (852, 'Mobile Communications', 3, 5);
insert into Course (c_id, title, credits, d_id) values (853, 'Franchising', 3, 2);
insert into Course (c_id, title, credits, d_id) values (854, 'Kinect', 3, 6);
insert into Course (c_id, title, credits, d_id) values (855, 'Equity Research', 3, 1);
insert into Course (c_id, title, credits, d_id) values (856, 'Gaming Industry', 3, 1);
insert into Course (c_id, title, credits, d_id) values (857, 'Marketing Communications', 3, 11);
insert into Course (c_id, title, credits, d_id) values (858, 'FM', 3, 1);
insert into Course (c_id, title, credits, d_id) values (859, 'Civil Society', 3, 12);
insert into Course (c_id, title, credits, d_id) values (860, 'BS7799', 3, 4);
insert into Course (c_id, title, credits, d_id) values (861, 'OEM negotiations', 3, 1);
insert into Course (c_id, title, credits, d_id) values (862, 'Freight Forwarding', 3, 12);
insert into Course (c_id, title, credits, d_id) values (863, 'Digital Marketing', 3, 5);
insert into Course (c_id, title, credits, d_id) values (864, 'Evidence', 3, 2);
insert into Course (c_id, title, credits, d_id) values (865, 'Medical Billing', 3, 3);
insert into Course (c_id, title, credits, d_id) values (866, 'MCAD', 3, 8);
insert into Course (c_id, title, credits, d_id) values (867, 'AMBA AHB', 3, 6);
insert into Course (c_id, title, credits, d_id) values (868, 'Rule Of Law', 3, 8);
insert into Course (c_id, title, credits, d_id) values (869, 'Vocal', 3, 2);
insert into Course (c_id, title, credits, d_id) values (870, 'Payments', 3, 11);
insert into Course (c_id, title, credits, d_id) values (871, 'ESB', 3, 10);
insert into Course (c_id, title, credits, d_id) values (872, 'MKS Integrity', 3, 5);
insert into Course (c_id, title, credits, d_id) values (873, 'Loss Prevention', 3, 5);
insert into Course (c_id, title, credits, d_id) values (874, 'MRI Software', 3, 5);
insert into Course (c_id, title, credits, d_id) values (875, 'General Ledger', 3, 10);
insert into Course (c_id, title, credits, d_id) values (876, 'Inventory Management', 3, 7);
insert into Course (c_id, title, credits, d_id) values (877, 'SS7', 3, 2);
insert into Course (c_id, title, credits, d_id) values (878, 'Sweaters', 3, 5);
insert into Course (c_id, title, credits, d_id) values (879, 'EWB', 3, 6);
insert into Course (c_id, title, credits, d_id) values (880, 'Employee Management', 3, 7);
insert into Course (c_id, title, credits, d_id) values (881, 'TSO', 3, 5);
insert into Course (c_id, title, credits, d_id) values (882, 'Lync', 3, 3);
insert into Course (c_id, title, credits, d_id) values (883, 'CBEST', 3, 12);
insert into Course (c_id, title, credits, d_id) values (884, 'TCPA', 3, 3);
insert into Course (c_id, title, credits, d_id) values (885, 'Jewelry', 3, 5);
insert into Course (c_id, title, credits, d_id) values (886, 'Overseas Experience', 3, 4);
insert into Course (c_id, title, credits, d_id) values (887, 'Small Business Marketing', 3, 7);
insert into Course (c_id, title, credits, d_id) values (888, 'Class III Medical Devices', 3, 4);
insert into Course (c_id, title, credits, d_id) values (889, 'Pyrosequencing', 3, 5);
insert into Course (c_id, title, credits, d_id) values (890, 'HTK', 3, 7);
insert into Course (c_id, title, credits, d_id) values (891, 'Dutch', 3, 1);
insert into Course (c_id, title, credits, d_id) values (892, 'Employee Training', 3, 4);
insert into Course (c_id, title, credits, d_id) values (893, 'Beer', 3, 9);
insert into Course (c_id, title, credits, d_id) values (894, 'Cd', 3, 12);
insert into Course (c_id, title, credits, d_id) values (895, 'SIP', 3, 4);
insert into Course (c_id, title, credits, d_id) values (896, 'Hadoop', 3, 2);
insert into Course (c_id, title, credits, d_id) values (897, 'FCIP', 3, 1);
insert into Course (c_id, title, credits, d_id) values (898, 'VRRP', 3, 7);
insert into Course (c_id, title, credits, d_id) values (899, 'Thermodynamics', 3, 2);
insert into Course (c_id, title, credits, d_id) values (900, 'GIS Modeling', 3, 9);
insert into Course (c_id, title, credits, d_id) values (901, 'TLC', 3, 9);
insert into Course (c_id, title, credits, d_id) values (902, 'NDE', 3, 3);
insert into Course (c_id, title, credits, d_id) values (903, 'Pigments', 3, 1);
insert into Course (c_id, title, credits, d_id) values (904, 'Science Journalism', 3, 12);
insert into Course (c_id, title, credits, d_id) values (905, 'XMLBeans', 3, 2);
insert into Course (c_id, title, credits, d_id) values (906, 'Distribution Center Operations', 3, 4);
insert into Course (c_id, title, credits, d_id) values (907, 'CST Microwave Studio', 3, 3);
insert into Course (c_id, title, credits, d_id) values (908, 'Ownership', 3, 4);
insert into Course (c_id, title, credits, d_id) values (909, 'Sony HDV', 3, 11);
insert into Course (c_id, title, credits, d_id) values (910, 'RCDD', 3, 12);
insert into Course (c_id, title, credits, d_id) values (911, 'TFT', 3, 1);
insert into Course (c_id, title, credits, d_id) values (912, 'OEM Management', 3, 3);
insert into Course (c_id, title, credits, d_id) values (913, 'Koha', 3, 10);
insert into Course (c_id, title, credits, d_id) values (914, 'Big 4', 3, 3);
insert into Course (c_id, title, credits, d_id) values (915, 'Epistemology', 3, 7);
insert into Course (c_id, title, credits, d_id) values (916, 'DGFT', 3, 8);
insert into Course (c_id, title, credits, d_id) values (917, 'Flexo', 3, 12);
insert into Course (c_id, title, credits, d_id) values (918, 'High Net Worth Individuals', 3, 11);
insert into Course (c_id, title, credits, d_id) values (919, 'Fiber Optics', 3, 1);
insert into Course (c_id, title, credits, d_id) values (920, 'VMI', 3, 3);
insert into Course (c_id, title, credits, d_id) values (921, 'RELAX NG', 3, 7);
insert into Course (c_id, title, credits, d_id) values (922, 'HMO', 3, 6);
insert into Course (c_id, title, credits, d_id) values (923, 'Document Imaging', 3, 10);
insert into Course (c_id, title, credits, d_id) values (924, 'Agarose Gel Electrophoresis', 3, 4);
insert into Course (c_id, title, credits, d_id) values (925, 'Boilers', 3, 6);
insert into Course (c_id, title, credits, d_id) values (926, 'Intercollegiate Athletics', 3, 1);
insert into Course (c_id, title, credits, d_id) values (927, 'TPA', 3, 3);
insert into Course (c_id, title, credits, d_id) values (928, 'Oil &amp; Gas Exploration', 3, 3);
insert into Course (c_id, title, credits, d_id) values (929, 'UCCE', 3, 8);
insert into Course (c_id, title, credits, d_id) values (930, 'DMAIC', 3, 3);
insert into Course (c_id, title, credits, d_id) values (931, 'MPLS Networking', 3, 6);
insert into Course (c_id, title, credits, d_id) values (932, 'Cognitive Psychology', 3, 3);
insert into Course (c_id, title, credits, d_id) values (933, 'Control Systems Design', 3, 7);
insert into Course (c_id, title, credits, d_id) values (934, 'WinForms', 3, 9);
insert into Course (c_id, title, credits, d_id) values (935, 'Juniper JNCIA', 3, 3);
insert into Course (c_id, title, credits, d_id) values (936, 'BMP', 3, 1);
insert into Course (c_id, title, credits, d_id) values (937, 'ASP.NET', 3, 11);
insert into Course (c_id, title, credits, d_id) values (938, 'ODS', 3, 12);
insert into Course (c_id, title, credits, d_id) values (939, 'Linux', 3, 8);
insert into Course (c_id, title, credits, d_id) values (940, 'SRED', 3, 7);
insert into Course (c_id, title, credits, d_id) values (941, 'Publishing', 3, 6);
insert into Course (c_id, title, credits, d_id) values (942, 'Jeet Kune Do', 3, 6);
insert into Course (c_id, title, credits, d_id) values (943, 'Erlang', 3, 1);
insert into Course (c_id, title, credits, d_id) values (944, 'Cisco VPN', 3, 5);
insert into Course (c_id, title, credits, d_id) values (945, 'Piping', 3, 8);
insert into Course (c_id, title, credits, d_id) values (946, '1H NMR', 3, 7);
insert into Course (c_id, title, credits, d_id) values (947, 'PDM Works', 3, 11);
insert into Course (c_id, title, credits, d_id) values (948, 'Wedding Photography', 3, 12);
insert into Course (c_id, title, credits, d_id) values (949, 'Gas Turbines', 3, 3);
insert into Course (c_id, title, credits, d_id) values (950, 'OKI', 3, 7);
insert into Course (c_id, title, credits, d_id) values (951, '7 QC Tools', 3, 5);
insert into Course (c_id, title, credits, d_id) values (952, 'Tk', 3, 8);
insert into Course (c_id, title, credits, d_id) values (953, 'Management by Objectives', 3, 10);
insert into Course (c_id, title, credits, d_id) values (954, 'HP Server Hardware', 3, 5);
insert into Course (c_id, title, credits, d_id) values (955, 'Product Development', 3, 2);
insert into Course (c_id, title, credits, d_id) values (956, 'Award Submissions', 3, 8);
insert into Course (c_id, title, credits, d_id) values (957, 'Jin Shin Jyutsu', 3, 11);
insert into Course (c_id, title, credits, d_id) values (958, 'WSIB Claims Management', 3, 8);
insert into Course (c_id, title, credits, d_id) values (959, 'GPS Navigation', 3, 9);
insert into Course (c_id, title, credits, d_id) values (960, 'LCM', 3, 8);
insert into Course (c_id, title, credits, d_id) values (961, 'Updos', 3, 11);
insert into Course (c_id, title, credits, d_id) values (962, 'RTP', 3, 6);
insert into Course (c_id, title, credits, d_id) values (963, 'IED', 3, 4);
insert into Course (c_id, title, credits, d_id) values (964, 'RHIT', 3, 5);
insert into Course (c_id, title, credits, d_id) values (965, 'Kickstart', 3, 2);
insert into Course (c_id, title, credits, d_id) values (966, 'Jigsaw', 3, 5);
insert into Course (c_id, title, credits, d_id) values (967, 'DSI', 3, 3);
insert into Course (c_id, title, credits, d_id) values (968, 'WS-Federation', 3, 5);
insert into Course (c_id, title, credits, d_id) values (969, 'UML', 3, 12);
insert into Course (c_id, title, credits, d_id) values (970, 'GCPs', 3, 5);
insert into Course (c_id, title, credits, d_id) values (971, 'PFEMA', 3, 3);
insert into Course (c_id, title, credits, d_id) values (972, 'Logging', 3, 6);
insert into Course (c_id, title, credits, d_id) values (973, 'VHF', 3, 4);
insert into Course (c_id, title, credits, d_id) values (974, 'WWII', 3, 9);
insert into Course (c_id, title, credits, d_id) values (975, 'HMIs', 3, 2);
insert into Course (c_id, title, credits, d_id) values (976, 'PKCS', 3, 3);
insert into Course (c_id, title, credits, d_id) values (977, 'FMV', 3, 7);
insert into Course (c_id, title, credits, d_id) values (978, 'BMC Patrol', 3, 8);
insert into Course (c_id, title, credits, d_id) values (979, 'CPI', 3, 6);
insert into Course (c_id, title, credits, d_id) values (980, 'PDH', 3, 12);
insert into Course (c_id, title, credits, d_id) values (981, 'UCP 600', 3, 3);
insert into Course (c_id, title, credits, d_id) values (982, 'RPG Free', 3, 9);
insert into Course (c_id, title, credits, d_id) values (983, 'Sports Psychology', 3, 5);
insert into Course (c_id, title, credits, d_id) values (984, 'Heavy Oil', 3, 1);
insert into Course (c_id, title, credits, d_id) values (985, 'Biopharmaceuticals', 3, 12);
insert into Course (c_id, title, credits, d_id) values (986, 'Insurance', 3, 8);
insert into Course (c_id, title, credits, d_id) values (987, 'Rhino 3D', 3, 2);
insert into Course (c_id, title, credits, d_id) values (988, 'Film Production', 3, 9);
insert into Course (c_id, title, credits, d_id) values (989, 'Mixed-Signal IC Design', 3, 6);
insert into Course (c_id, title, credits, d_id) values (990, 'HSQE', 3, 2);
insert into Course (c_id, title, credits, d_id) values (991, 'BMV', 3, 1);
insert into Course (c_id, title, credits, d_id) values (992, 'Smarty', 3, 3);
insert into Course (c_id, title, credits, d_id) values (993, 'TDP', 3, 5);
insert into Course (c_id, title, credits, d_id) values (994, 'DHCPv6', 3, 3);
insert into Course (c_id, title, credits, d_id) values (995, 'Aviation Security', 3, 4);
insert into Course (c_id, title, credits, d_id) values (996, 'ISO 13485', 3, 9);
insert into Course (c_id, title, credits, d_id) values (997, 'Event Planning', 3, 2);
insert into Course (c_id, title, credits, d_id) values (998, 'ISM', 3, 4);
insert into Course (c_id, title, credits, d_id) values (999, 'European Markets', 3, 1);
insert into Course (c_id, title, credits, d_id) values (1000, 'IEC 61508', 3, 10);
