use [391];
SET IDENTITY_INSERT [dbo].[Student] ON;
GO
INSERT INTO dbo.Student ([s_id],[last_name],[first_name],[gender]) VALUES(1, 'Alejo', 'Aaron', 'm')
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(2, 'Ammouneh', 'Omar', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(3, 'Areekadan','Nick', 'm')
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(4, 'Arora','Chaahat', 'f') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(5, 'Brownlee','Samuel', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(6, 'Campbell','Charlene', 'f') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(7, 'DCruz','Mark' , 'm')
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(8, 'Dobosz','Dominic', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(9,'Donovan','Daniel', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(10,'Ference','Brittney', 'f')   
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(11,'Ghebretatios','Matios', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(12,'Hamilton','Alex', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(13,'Harker','Brant Russell', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(14,'Infante','Jethro', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(15,'Javed','Muhammad Hamza', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(16,'Khan','Ayesha', 'f') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(17,'Kim','Christine Mee', 'f')
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(18,'Kwon','Benjamin', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(19,'Lai','Jason', 'm')
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(20,'Leechen','Terry', 'm')  
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(21,'Moise','Vlad', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(22,'Nakamura','Jasper', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(23,'Nguyen','Axel', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(24,'Polywkan','Adam', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(25,'Prajapati','Rushabh Urvashi Umeshkumar', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(26,'Said','Mark Samy', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(27,'Sieben','Carter Joseph', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(28,'Sison','Maria Karina Beatrice Ablang', 'f')  
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(29,'Sniezek','Korey Mitchell', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(30,'Stewart','Evan', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(31,'Swensrude','Zachary Josef', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(32,'Tadros','Victor', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(33,'Vanderzyl','Barnaby', 'm') 
INSERT INTO dbo.Student(s_id,last_name,first_name,gender) VALUES(34,'Walsh','Ben', 'm')
SET IDENTITY_INSERT dbo.Student OFF;



