insert into Course (course_id, Cname, dept, credits) values (1, 'Government', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (2, 'HTK', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (3, 'Oligonucleotides', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (4, 'CSI', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (5, 'Elder Care', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (6, 'ILS', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (7, 'PPAP', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (8, 'UCP 600', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (9, 'PPAPs', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (10, 'e-QIP', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (11, 'Outlook', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (12, 'Marketing', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (13, 'Tubing', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (14, 'CBM', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (15, 'FX Options', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (16, 'Nielsen Data', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (17, 'MW', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (18, 'PBS', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (19, 'DV', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (20, 'AOI', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (21, 'TCAP', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (22, 'FrameMaker', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (23, 'FTTH', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (24, 'Soft Skills', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (25, 'Illustration', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (26, 'Axles', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (27, 'XACT', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (28, 'Durable Medical Equipment', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (29, 'ENOVIA LCA', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (30, 'Acute Care', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (31, 'Special Events Coordination', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (32, 'YAML', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (33, 'NCSim', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (34, 'LSI', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (35, 'Airline Ticketing', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (36, 'WPF', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (37, 'Public Speaking', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (38, 'IntelliJ IDEA', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (39, 'NAS', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (40, 'DFMA', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (41, 'Gmail', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (42, 'Real Estate', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (43, 'SRT', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (44, 'Vtiger', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (45, 'Contact Centers', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (46, 'Psychometrics', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (47, 'Renewable Energy', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (48, 'International Human Rights', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (49, 'NS2', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (50, 'PTT', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (51, 'DSLAM', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (52, 'Urbanism', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (53, 'XSI', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (54, 'WAN', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (55, 'IICRC Certified', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (56, 'EEO Reporting', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (57, 'IBM iSeries', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (58, 'HP Service Manager', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (59, 'OSI Model', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (60, 'SNOMED', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (61, 'Supply Management', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (62, 'Long-term Care', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (63, 'NSA-IAM', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (64, 'Finite Element Analysis', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (65, 'DNS Administration', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (66, 'User Experience Design', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (67, 'Powers of Attorney', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (68, 'PVCS', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (69, 'RPR', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (70, 'Cash Flow', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (71, 'WHIMS', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (72, 'XML', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (73, 'EELS', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (74, 'GUI development', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (75, 'Rehabilitation Psychology', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (76, 'Lyris ListManager', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (77, 'MPEG Streamclip', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (78, 'GIS Application', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (79, 'HBA', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (80, 'Target Costing', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (81, 'Banquets', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (82, 'Obstetrics', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (83, 'Clerical Skills', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (84, 'LSO', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (85, 'CQI', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (86, 'NRA', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (87, 'Childcare', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (88, 'RQM', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (89, 'HDRI', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (90, 'Easements', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (91, 'MMIC', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (92, 'ILT', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (93, 'EIM', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (94, 'Rail', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (95, 'Zend', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (96, 'Raw Materials', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (97, 'Hydraulic Fracturing', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (98, 'DJ', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (99, 'Business Journalism', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (100, 'Affiliate Marketing', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (101, 'PFGE', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (102, 'LBO', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (103, 'KWI', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (104, 'PCI Standards', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (105, 'Xdebug', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (106, 'BTLS', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (107, 'Events Coordination', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (108, 'Outdoors', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (109, 'FX Trading', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (110, 'TIG Welding', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (111, 'SQL', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (112, 'Uniform Combined State Law', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (113, 'VRF', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (114, 'iHotelier', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (115, 'GGY Axis', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (116, 'eGRC', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (117, 'TCAS', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (118, 'AED', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (119, 'UDS', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (120, 'Irrigation Management', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (121, 'Ext JS', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (122, 'RTM', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (123, 'MLOAD', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (124, 'IT Governance', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (125, 'Hand Knitting', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (126, 'EoMPLS', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (127, 'GSE', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (128, 'FDS', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (129, 'VDI', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (130, 'Xen', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (131, 'Physician Relations', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (132, 'Outdoors', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (133, 'GTP', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (134, 'Flash Animation', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (135, 'VHDL-AMS', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (136, 'Mechanical Engineering', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (137, 'ENOVIA LCA', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (138, 'Epic Systems', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (139, 'AHP', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (140, 'Typo3', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (141, 'HR Project Management', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (142, 'Olympic Lifting', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (143, 'Consumer Electronics', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (144, 'DDNS', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (145, 'JCIDS', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (146, 'Youth Programs', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (147, 'VTS', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (148, 'Church Events', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (149, 'Brand Equity', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (150, 'Ebay Sales', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (151, 'JAX-RPC', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (152, 'HR Consulting', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (153, 'Fertility', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (154, 'Business Process Improvement', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (155, 'Electronic Warfare', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (156, 'ZeroMQ', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (157, 'Siding', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (158, 'Ocean Freight', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (159, 'Full-life Cycle Recruiting', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (160, 'PBMC isolation', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (161, 'Online Lead Generation', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (162, 'AAC', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (163, 'DMC', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (164, 'MWS', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (165, 'Aeronautics', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (166, 'Tds', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (167, 'Sustainability', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (168, 'Pyxis', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (169, 'Iron', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (170, 'Power Electronics', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (171, 'Autodesk Inventor', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (172, 'VLSI', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (173, 'RCDD', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (174, 'CQ', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (175, 'Google Docs', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (176, 'CPLD', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (177, 'Jet Engines', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (178, 'DX200', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (179, 'JDK', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (180, 'HDI Support Center Analyst', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (181, 'Call Centers', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (182, 'Citrix XenDesktop', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (183, 'IICRC Certifications', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (184, 'GMI', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (185, 'Animal Work', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (186, 'OTM', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (187, 'Usability Testing', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (188, 'Medicine', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (189, 'Rural Development', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (190, 'Local Government', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (191, 'SAP MDM', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (192, 'WinForms', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (193, 'GC-MS', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (194, 'Genomics', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (195, 'Hair Cutting', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (196, 'EPANET', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (197, 'AutoCAD', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (198, 'Jigsaw', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (199, 'Attorneys', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (200, 'SNL', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (201, 'MCEV', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (202, 'PC Anywhere', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (203, 'DVD Architect', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (204, 'Sniffer', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (205, 'GPON', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (206, 'Business Rules', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (207, 'Electrical Engineering', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (208, 'Interactive TV', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (209, 'Retail', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (210, 'Switchgear', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (211, 'Dysphagia', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (212, 'Static Timing Analysis', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (213, 'Hazardous Waste Management', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (214, 'VSAT', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (215, 'iHistorian', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (216, 'Switching', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (217, 'Appointment Scheduling', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (218, 'BDD', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (219, 'WLM', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (220, 'Fund Administration', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (221, 'GSS', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (222, 'Practice CS', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (223, 'Three.js', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (224, 'Air Traffic Control', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (225, 'Regulatory Affairs', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (226, 'RS Means', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (227, 'Health Promotion', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (228, 'Employee Training', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (229, 'Bridge', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (230, 'Alumni Relations', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (231, 'ASP.NET MVC', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (232, 'GTS', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (233, 'Cyberlaw', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (234, 'Occupational Medicine', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (235, 'Team Effectiveness', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (236, 'Perl', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (237, 'Organization Skills', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (238, 'Juniper Technologies', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (239, 'Event Production', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (240, 'Web TV', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (241, 'MDSD', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (242, 'Handmade Jewelry', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (243, 'IFS ERP', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (244, 'Akka', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (245, 'Object Pascal', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (246, 'Testing Types', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (247, 'GFP', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (248, 'Yard Management', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (249, 'Audio Typing', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (250, 'SPC', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (251, 'IVIVC', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (252, 'SIP', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (253, 'MPEG2', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (254, 'Cash Flow', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (255, 'Czech', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (256, 'Oxy-acetylene', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (257, 'Vendor Management', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (258, 'Euphonium', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (259, 'Gardening', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (260, 'GIMP', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (261, 'International Economics', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (262, '.NET', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (263, 'Sponsorship', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (264, 'LLDP', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (265, 'Brocade Fibre Switches', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (266, 'Carrier Ethernet', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (267, 'EWB', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (268, 'Sports Injuries', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (269, 'EOI', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (270, 'Overseas Production', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (271, 'Reverse Logistics', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (272, 'Watercolor', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (273, 'IBM Rational Rhapsody', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (274, 'Embedded C', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (275, 'Branding &amp; Identity', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (276, 'Customs Regulations', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (277, 'Store Management', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (278, 'Rock Climbing', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (279, 'TPU', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (280, 'WUFI', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (281, 'Food', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (282, 'New Business Development', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (283, 'Small Business Lending', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (284, 'Eggplant', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (285, 'vBulletin', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (286, 'Contact Centers', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (287, 'Managed Services', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (288, 'OJEU', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (289, 'Emergency Room', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (290, 'GPFS', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (291, 'Fences', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (292, 'NMR', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (293, 'Xplan', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (294, 'Onboarding', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (295, 'Commercial Piloting', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (296, 'Notary Public', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (297, 'Hodes IQ', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (298, 'Climate Change', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (299, 'Nielsen Data', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (300, 'NLS', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (301, 'PPP', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (302, 'TF-CBT', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (303, 'NCIE', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (304, 'Chi Nei Tsang', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (305, 'Xenix', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (306, 'Feature Articles', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (307, 'Cfengine', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (308, 'SSH Client', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (309, 'MyEclipse', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (310, 'Private Duty', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (311, 'WSIB Claims Management', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (312, 'PTLLS', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (313, 'VLSI CAD', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (314, 'European Union Politics', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (315, 'Poka Yoke', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (316, 'Online Research', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (317, 'Nutritional Counseling', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (318, 'RS485', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (319, 'TSP', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (320, 'Kitchen Remodeling', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (321, 'AOI', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (322, 'Interpersonal Skills', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (323, 'JSLint', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (324, 'European Markets', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (325, 'Drywall', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (326, 'QFD', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (327, 'NICET', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (328, 'AX 2009', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (329, 'Client Aquisition', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (330, 'Numerical Simulation', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (331, 'Ion Implantation', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (332, 'Culinary Skills', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (333, 'Special Effects Makeup', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (334, 'Video Games', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (335, 'Aqualogic', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (336, 'EBP', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (337, 'Gymnastics', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (338, 'Character Rigging', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (339, 'European Computer Driving Licence', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (340, 'Zultys', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (341, 'International Sales', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (342, 'WC', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (343, 'Google Apps', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (344, 'Newspapers', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (345, 'AU', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (346, 'GPRS', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (347, 'RF Scanners', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (348, 'Numerical Simulation', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (349, 'GIS systems', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (350, 'HD Camera Operation', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (351, 'Ethical Hacking', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (352, 'Usability', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (353, 'SOA', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (354, 'LSI', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (355, 'mTAB', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (356, 'LTO', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (357, 'JWICS', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (358, 'Blogger', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (359, 'Buyers', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (360, 'Real Estate License', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (361, 'IBM Utilities', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (362, 'LLVM', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (363, 'DDNS', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (364, 'Brand Awareness', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (365, 'Vocal', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (366, 'qRT-PCR', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (367, 'GFAAS', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (368, 'TWS', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (369, 'Physician Relations', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (370, 'Apache', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (371, 'CSLA', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (372, 'Windows 7', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (373, 'DNS Administration', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (374, 'Visual Identity', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (375, 'MVS', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (376, 'RFQ Development', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (377, 'RF Planning', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (378, 'Program Management', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (379, 'Trials', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (380, 'Cost Benefit', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (381, 'Kaizen Leadership', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (382, 'QIP', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (383, 'TCAP', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (384, 'EEG', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (385, 'MBCS', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (386, 'Hunting', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (387, 'Customer Satisfaction', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (388, 'PFGE', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (389, 'Analysis', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (390, 'FP', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (391, 'Emergency Nursing', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (392, 'ATG CSC', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (393, 'IR', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (394, 'Medical Devices', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (395, 'Architectural Illustration', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (396, 'IFW', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (397, 'Digital Electronics', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (398, 'Medical Ultrasound', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (399, 'RSVP-TE', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (400, 'Graphic Illustrations', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (401, 'OLEDB', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (402, 'Teamwork', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (403, 'Object Oriented Software', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (404, 'Apparel', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (405, 'NATO', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (406, 'MBCS', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (407, 'FF&amp;E Procurement', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (408, 'Inventory Control', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (409, 'GNS3', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (410, 'MBCS', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (411, 'BCA Protein Assay', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (412, 'Volunteer Management', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (413, 'Kickstart', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (414, 'NS-2', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (415, 'OECD', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (416, 'Software Implementation', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (417, 'Shopping Centers', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (418, 'DTDs', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (419, 'SNL', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (420, 'z/OS', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (421, 'QAD', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (422, 'LSAMS', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (423, 'Hygiene', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (424, 'JCL', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (425, 'Norwegian', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (426, 'Radio', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (427, 'Amazon VPC', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (428, 'PPTP', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (429, 'SQL Loader', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (430, 'FDICIA', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (431, 'HF', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (432, 'DBI', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (433, 'DVB-T', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (434, 'Spreadsheets', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (435, 'Ethernet', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (436, 'CVS', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (437, 'HTA', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (438, 'Music Education', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (439, 'DNA electrophoresis', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (440, 'NRP Instruction', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (441, 'Jewish History', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (442, 'SX.enterprise', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (443, 'HQL', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (444, 'Classical Guitar', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (445, 'PDF Creator', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (446, 'APO SNP', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (447, 'Occupational Health', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (448, 'Whole House Renovations', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (449, 'EP', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (450, 'Apartments', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (451, 'Water', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (452, 'Izotope RX', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (453, 'Alzheimer&#39;s Disease', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (454, 'Typesetting', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (455, 'Justice', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (456, 'VLC', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (457, 'HR Policies', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (458, 'Supplier Evaluation', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (459, 'NPL', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (460, 'Bodywork', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (461, 'Tcl-Tk', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (462, 'Ultrasonic Testing', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (463, 'NVR', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (464, 'Ubuntu', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (465, 'RTB', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (466, 'SFR Certified', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (467, 'BSC', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (468, 'Interior Design', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (469, 'MPBGP', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (470, 'Telephone Skills', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (471, 'Real Estate Financing', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (472, 'JTest', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (473, 'TS2', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (474, 'General Surgery', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (475, 'Www', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (476, 'Pro-IV', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (477, 'VMware Certified Professional', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (478, 'GTAW', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (479, 'Krakatoa', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (480, 'Bathrooms', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (481, 'CX', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (482, 'BFSI', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (483, 'Wholesale Purchasing', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (484, 'MQX', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (485, 'MDRs', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (486, 'NMLS', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (487, 'SI', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (488, 'Rock Music', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (489, 'Key Account Development', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (490, 'Slip &amp; Fall', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (491, 'Sensory Evaluation', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (492, 'MCITP', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (493, 'DBUnit', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (494, 'PC Anywhere', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (495, 'DMAIC', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (496, 'Oracle Identity Manager', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (497, 'Cross-functional Team Leadership', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (498, 'Luminex', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (499, 'RS232', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (500, 'Multithreading', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (501, 'Wwise', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (502, 'Online Lead Generation', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (503, 'International Sales', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (504, 'NSE', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (505, 'VMI Programs', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (506, 'UGS', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (507, 'Node.js', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (508, 'Avionics', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (509, 'Job Costing', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (510, 'Site Development', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (511, 'DCM', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (512, 'xUnit', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (513, 'CTR', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (514, 'Variable Frequency Drives', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (515, 'Executive Administrative Assistance', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (516, 'SAP OM', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (517, 'Pro Tools', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (518, 'RFID', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (519, 'RPR', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (520, 'Corporate Law', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (521, 'ASP.NET', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (522, 'NBAP', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (523, 'PS3', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (524, 'Technical Support', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (525, 'JDO', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (526, 'TMJ Treatment', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (527, 'FM', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (528, 'Latin American Studies', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (529, 'Shell Scripting', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (530, 'For Sale By Owner', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (531, 'TUPE', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (532, 'HV', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (533, 'Torts', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (534, 'YUM', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (535, 'Chamber Music', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (536, 'Crossbeam XOS', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (537, 'DNA quantification', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (538, 'CCNP Security', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (539, 'Lucene', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (540, 'Aerial Lifts', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (541, 'TPE', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (542, 'Hospitality Industry', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (543, 'PMAs', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (544, 'Rugby Union', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (545, 'Private Piloting', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (546, 'Job Fairs', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (547, 'Aquatic Ecology', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (548, 'Fund Administration', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (549, 'Bathrooms', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (550, 'Watercolor Illustration', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (551, 'Frozen Food', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (552, 'Federal Grants Management', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (553, 'NCSim', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (554, 'Sports Medicine', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (555, 'CentOS', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (556, 'Rhinoceros', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (557, 'SAP MM Module', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (558, 'Django', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (559, 'Business Intelligence', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (560, 'Lyris', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (561, 'JNA', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (562, 'Military Training', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (563, 'Music Festivals', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (564, 'WSDL', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (565, 'TCP/IP', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (566, 'GPS Applications', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (567, 'SGML', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (568, 'RMS', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (569, 'DBU', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (570, 'Ministry Of Defence', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (571, 'RFP Generation', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (572, 'Node.js', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (573, 'Cybercrime', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (574, 'Weddings', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (575, 'CDMA2000', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (576, 'IP CCTV', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (577, 'LPT', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (578, 'Analytical Skills', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (579, 'DCS', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (580, 'Black &amp; White', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (581, 'MCITP', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (582, 'Visual SVN', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (583, 'GMDSS', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (584, 'Pallet Jack', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (585, 'FCoE', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (586, 'Pumps', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (587, 'Omron', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (588, 'Public Safety', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (589, 'Training Delivery', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (590, 'IVIVC', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (591, 'TFT', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (592, 'Ghost Imaging', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (593, 'QSI', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (594, 'RTC', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (595, 'Vehicles', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (596, 'UDP', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (597, 'European Computer Driving Licence', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (598, 'Dysarthria', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (599, 'IGRP', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (600, 'Pro II', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (601, 'Shared Services', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (602, 'HBV', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (603, 'PDMS', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (604, 'Claims Management', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (605, 'UK Immigration', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (606, 'Bootstrap', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (607, 'Mac OS', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (608, 'EBPP', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (609, 'Capacity Building', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (610, 'HDPE', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (611, 'Icon Design', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (612, 'ISM', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (613, 'Yardi Enterprise', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (614, 'Kontakt', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (615, 'Histology', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (616, 'DBWorks', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (617, 'UK Corporation Tax', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (618, 'Oracle RDC', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (619, 'Earth Science', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (620, 'Inventory Control', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (621, 'Blues', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (622, 'GSX', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (623, 'Ice Hockey', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (624, 'VRRP', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (625, 'MGCP', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (626, 'DNA replication', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (627, 'Historical Research', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (628, 'XMPie', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (629, 'Science', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (630, 'Kenan FX', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (631, 'Driven By Results', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (632, 'Program Management', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (633, 'Kernel Programming', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (634, 'LLC', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (635, 'Creative Non-fiction', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (636, 'Digital Signal Processors', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (637, 'Job Costing', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (638, 'Rx', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (639, 'RPG Free', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (640, 'CQG', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (641, 'QMF', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (642, 'DVB-H', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (643, 'Servers', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (644, 'Sensory Evaluation', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (645, 'MCEV', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (646, 'Slackware', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (647, 'KML', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (648, 'ATP', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (649, 'Radio Promotions', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (650, 'Team Leadership', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (651, 'NLRB', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (652, 'Call Centers', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (653, 'PVST+', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (654, 'Toyota Production System', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (655, 'Project Estimation', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (656, 'LTL', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (657, 'Executive Management', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (658, 'Consulting', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (659, 'TNS', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (660, 'DTE', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (661, 'Jigsaw', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (662, 'Diabetes', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (663, 'Speech Writing', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (664, 'Cash Management', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (665, 'PWB', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (666, 'Creative Strategy', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (667, 'Cisco VPN', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (668, 'New Media', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (669, 'Teacher Training', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (670, 'Blueprint Reading', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (671, 'Organizational Development', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (672, 'Apache', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (673, 'Tally ERP', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (674, 'IT Strategy', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (675, 'RCP', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (676, 'Office Management', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (677, 'BSR Advance', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (678, 'Nutrition Education', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (679, 'Urban Planning', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (680, 'eTOM', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (681, 'TPM', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (682, 'Product Knowledge', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (683, 'Fashion Design', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (684, 'LTSP', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (685, 'RQM', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (686, 'Node.js', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (687, 'Kaspersky', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (688, 'HR Project Management', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (689, 'Community Organizing', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (690, 'High Yield', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (691, 'Software Implementation', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (692, 'XUL', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (693, 'RTL Verification', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (694, 'Urban Search &amp; Rescue', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (695, 'Vulnerability Management', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (696, 'T-SQL', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (697, 'Farms', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (698, 'Zimbra', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (699, 'XML Gateway', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (700, 'Histology', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (701, 'Process Improvement', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (702, 'Water Quality', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (703, 'PMB', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (704, 'HMRC enquiries', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (705, 'TTCN', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (706, 'Lung', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (707, 'Layout', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (708, 'Team Leadership', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (709, 'SRX', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (710, 'PNF', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (711, 'DNA microarray', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (712, 'Lyricist', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (713, 'Nanoparticles', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (714, 'AV', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (715, 'TWS', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (716, 'BGA', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (717, 'Zend Studio', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (718, 'ADP HRB', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (719, 'Substance Abuse Prevention', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (720, 'Surveying', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (721, 'Fund Administration', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (722, 'Uranium', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (723, 'Case Management', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (724, 'VRTX', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (725, 'PDS', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (726, 'LSL', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (727, 'ERP', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (728, 'UPS Shipping', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (729, 'VPM', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (730, 'Media Planning', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (731, 'PGW', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (732, 'WCF', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (733, 'JProbe', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (734, 'OC RDC', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (735, 'Education', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (736, 'Clinical Supervision', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (737, 'IVIVC', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (738, 'Zillow', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (739, 'HP XP', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (740, 'Winning Others Over', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (741, 'Kronos WFC', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (742, 'Technical Support', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (743, 'Mystery Shopping', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (744, 'RSS', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (745, 'Jeet Kune Do', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (746, 'HR Solutions', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (747, 'Content Strategy', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (748, 'European Politics', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (749, 'EEO', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (750, 'Mergers &amp; Acquisitions', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (751, 'CDM Coordinator', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (752, 'Ektron', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (753, 'IRB', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (754, 'Breaking News', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (755, 'Erosion Control', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (756, 'QLab', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (757, 'WSGI', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (758, 'OOAD', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (759, 'Receptionist Duties', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (760, 'GHS', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (761, 'TPU', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (762, 'VSX', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (763, 'Video Production', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (764, 'Groundwater', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (765, 'HP Networking', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (766, 'Blueprint Reading', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (767, 'Finite Element Analysis', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (768, 'Sketching', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (769, 'Tenacious Work Ethic', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (770, 'Lean Manufacturing', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (771, 'XRF', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (772, 'iHistorian', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (773, 'TSP', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (774, 'International Trade', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (775, 'Contact Centers', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (776, 'Ambulance', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (777, 'Petroleum Geology', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (778, 'Disability Insurance', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (779, 'NWDS', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (780, 'Afghanistan', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (781, 'PDCA', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (782, 'Know-how', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (783, 'JCIDS', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (784, 'Illustrator', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (785, 'XLSTAT', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (786, 'Reverse Logistics', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (787, 'Information Architecture', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (788, 'MSS', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (789, 'Eiffel', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (790, 'Kronos', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (791, 'Ultra Low Latency', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (792, 'Ember.js', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (793, 'Supply Chain', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (794, 'Cvent', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (795, 'Banking', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (796, 'Up-selling', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (797, 'Running', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (798, 'Financial Advisory', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (799, 'QAM', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (800, 'Audio Typing', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (801, 'International Sales', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (802, 'Nitrous Oxide', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (803, 'OAM', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (804, 'DFLSS', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (805, 'Cerner CCL', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (806, 'Weddings', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (807, 'Google Docs', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (808, 'PML', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (809, 'Funding', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (810, 'First Time Home Sellers', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (811, 'Bank Reconciliation', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (812, 'UV Mapping', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (813, 'Commercial Photography', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (814, 'CDMA', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (815, 'CD packaging', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (816, 'Drip Irrigation', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (817, 'AMI', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (818, 'Octave', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (819, 'DCF Valuation', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (820, 'Athletic Training', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (821, 'Radiology', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (822, 'CPM Scheduling', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (823, 'PL/SQL', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (824, 'Outsourcing Management', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (825, 'Document Drafting', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (826, 'ILS', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (827, 'Econometrics', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (828, 'QSIG', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (829, 'DLC', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (830, 'Novell Netware', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (831, 'Zotero', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (832, 'DDL', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (833, 'VXML', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (834, 'Jitterbit', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (835, 'DP', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (836, 'Ukulele', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (837, 'Alcohol Awareness', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (838, 'Consumer Electronics', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (839, 'Digital Photography', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (840, 'GPRS', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (841, 'Switchboard', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (842, 'Teaching', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (843, 'DNS Management', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (844, 'RTI', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (845, 'Interest Rate Swaps', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (846, 'CSA 2010', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (847, 'Drainage', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (848, 'BBEdit', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (849, 'CICS', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (850, 'HP Server Hardware', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (851, 'Commercial Aviation', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (852, 'Microsoft Office', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (853, 'Fund Of Funds', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (854, 'Occupational Therapy', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (855, 'Customs Regulations', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (856, 'TSW', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (857, 'Psychopharmacology', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (858, 'CTIOS', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (859, 'HDF5', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (860, 'PFT', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (861, 'NMock', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (862, 'BD+C', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (863, 'Big Data', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (864, 'Blueprint Reading', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (865, 'UE', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (866, 'Telephone Skills', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (867, 'XPDL', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (868, 'JNA', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (869, 'AJAX', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (870, 'iReport', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (871, 'Juvenile Delinquency', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (872, 'Start-up Consulting', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (873, 'XTRACT', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (874, 'Corporate FP&amp;A', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (875, 'Teaching Writing', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (876, 'MCH', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (877, 'NICU', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (878, 'HMIs', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (879, 'Therapists', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (880, 'EWP', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (881, 'WPC', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (882, 'Data Modeling', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (883, 'Lucene', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (884, 'Validation', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (885, 'Blue Ocean Strategy', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (886, 'WLM', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (887, 'LP', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (888, 'Journal Entries', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (889, 'Gutters', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (890, 'Hoshin Kanri', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (891, 'Software Design', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (892, 'MCSA + Messaging', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (893, 'Church Growth', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (894, 'ASP.NET MVC', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (895, 'Updos', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (896, 'Pastoral Counseling', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (897, 'CI', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (898, 'Vtiger', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (899, 'Hiring', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (900, 'ILT', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (901, 'Board Development', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (902, 'Aquisition', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (903, 'Academic Tutoring', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (904, 'Urdu', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (905, 'LLU', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (906, 'Luciferase Assay', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (907, 'Award Submissions', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (908, 'Microsoft Dynamics SL', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (909, 'Student Financial Aid', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (910, 'Laboratory Skills', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (911, 'RMAN', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (912, 'TWiki', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (913, 'Judo', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (914, 'Electronic Payments', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (915, 'TSW', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (916, 'Digital Journalism', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (917, 'Oracle OLAP', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (918, 'Work Effectively', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (919, 'Fine Dining', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (920, 'Visual Effects', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (921, 'Administrative Assistance', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (922, 'USDA Rural Housing', 'English', 3);
insert into Course (course_id, Cname, dept, credits) values (923, 'GDP', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (924, 'ABAP', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (925, 'Kindergarten', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (926, 'Strategic Communications', 'Finance', 3);
insert into Course (course_id, Cname, dept, credits) values (927, 'IBM BPM', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (928, 'Call center start-up', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (929, 'Staff Development', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (930, 'UED', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (931, 'Foreign Policy', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (932, 'Mobile TV', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (933, 'PDH', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (934, 'Directing Others', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (935, 'TMDLs', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (936, 'Corporate Communications', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (937, 'GCF', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (938, 'Airline Management', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (939, 'LPN', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (940, 'Childhood Obesity', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (941, 'Music Videos', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (942, 'Win CVS', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (943, 'RDz', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (944, 'USDA', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (945, 'FCS', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (946, 'JFreeChart', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (947, 'ATP', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (948, 'World War II', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (949, 'XMPie', 'Physical Sciences', 3);
insert into Course (course_id, Cname, dept, credits) values (950, 'MHRA', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (951, 'RTL Design', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (952, 'IT Hardware Support', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (953, 'Loans', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (954, 'GLP', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (955, 'Psychological Testing', 'Psychology', 3);
insert into Course (course_id, Cname, dept, credits) values (956, 'Process Optimization', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (957, 'HDTV', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (958, 'IVIVC', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (959, 'Events Organisation', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (960, 'Visual Studio', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (961, 'MYOB', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (962, 'HST', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (963, 'Gold', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (964, 'FX Options', 'Design', 3);
insert into Course (course_id, Cname, dept, credits) values (965, 'AXE', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (966, 'Video Production', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (967, 'Airworthiness', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (968, 'Tumblr', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (969, 'Rural Development', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (970, 'GIMP', 'Human Health', 3);
insert into Course (course_id, Cname, dept, credits) values (971, 'MMO', 'Bio-Science', 3);
insert into Course (course_id, Cname, dept, credits) values (972, 'RS485', 'Sociology', 3);
insert into Course (course_id, Cname, dept, credits) values (973, 'Eyelash &amp; Eyebrow Tinting', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (974, 'Americans with Disabilities Act', 'Music', 3);
insert into Course (course_id, Cname, dept, credits) values (975, 'Fly Tying', 'Social Work', 3);
insert into Course (course_id, Cname, dept, credits) values (976, 'CDM', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (977, 'Construction', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (978, 'FCPA', 'Humanities', 3);
insert into Course (course_id, Cname, dept, credits) values (979, 'Pastoral Care', 'Human Services', 3);
insert into Course (course_id, Cname, dept, credits) values (980, 'NFL', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (981, 'MMIC', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (982, 'UHV', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (983, 'Technical Documentation', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (984, 'JSP', 'Mathematics', 3);
insert into Course (course_id, Cname, dept, credits) values (985, 'Bylaws', 'Youth Care', 3);
insert into Course (course_id, Cname, dept, credits) values (986, 'Kodaly', 'Human Resources', 3);
insert into Course (course_id, Cname, dept, credits) values (987, 'Cloud Computing', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (988, 'Guardianship', 'Computer Science', 3);
insert into Course (course_id, Cname, dept, credits) values (989, 'ETFs', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (990, 'SGSN', 'Nursing', 3);
insert into Course (course_id, Cname, dept, credits) values (991, 'Microcontrollers', 'Studio Arts', 3);
insert into Course (course_id, Cname, dept, credits) values (992, 'Performance Management', 'Health Systems', 3);
insert into Course (course_id, Cname, dept, credits) values (993, 'OTDR', 'Performance', 3);
insert into Course (course_id, Cname, dept, credits) values (994, 'iOS Design', 'Theatre', 3);
insert into Course (course_id, Cname, dept, credits) values (995, 'Animal Work', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (996, 'Awareness Raising', 'Political Science', 3);
insert into Course (course_id, Cname, dept, credits) values (997, 'NDMP', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (998, 'Telecom BSS', 'Communication', 3);
insert into Course (course_id, Cname, dept, credits) values (999, 'NMT', 'Public Safety', 3);
insert into Course (course_id, Cname, dept, credits) values (1000, 'CPA', 'Human Resources', 3);
